// ============================================================
// Agentic Dashboard — Inventory Mock Data Service
// ============================================================
// 200 items across 10 collections, 50 forecast items, product classification

import { delay } from "@/lib/utils";
import type {
  InventoryItem,
  ForecastItem,
  ProductClassification,
  InventoryCategory,
  ProductStatus,
  PriorityLevel,
} from "@/types";

function randomBetween(min: number, max: number, decimals = 0): number {
  const val = Math.random() * (max - min) + min;
  return decimals > 0
    ? Math.round(val * 10 ** decimals) / 10 ** decimals
    : Math.round(val);
}

// ---------------------------------------------------------------------------
// Inventory Items — 200 products across 10 collections (20 each)
// ---------------------------------------------------------------------------

const inventory: InventoryItem[] = [
  // ── Summer Breeze (SB) ──────────────────────────────────────────────
  { sku: "SB-DR-001", productName: "Summer Breeze Midi Dress", currentStock: 210, incomingStock: 100, salesLast30Days: 145, daysRemaining: 43, dailySalesVelocity: 4.83, category: "fast", status: "in_stock", supplier: "Baltic Textiles OÜ", collection: "Summer Breeze", unitCost: 38, unitPrice: 140, reorderPoint: 75 },
  { sku: "SB-DR-002", productName: "Breeze Ruffle Maxi Dress", currentStock: 88, incomingStock: 0, salesLast30Days: 62, daysRemaining: 43, dailySalesVelocity: 2.07, category: "normal", status: "in_stock", supplier: "Baltic Textiles OÜ", collection: "Summer Breeze", unitCost: 44, unitPrice: 170, reorderPoint: 60 },
  { sku: "SB-DR-003", productName: "Sunlit Tiered Dress", currentStock: 3, incomingStock: 200, salesLast30Days: 48, daysRemaining: 2, dailySalesVelocity: 1.6, category: "fast", status: "critical", supplier: "Nordic Stitch AS", collection: "Summer Breeze", unitCost: 42, unitPrice: 155, reorderPoint: 50 },
  { sku: "SB-TP-001", productName: "Breeze Off-Shoulder Top", currentStock: 156, incomingStock: 0, salesLast30Days: 98, daysRemaining: 48, dailySalesVelocity: 3.27, category: "fast", status: "in_stock", supplier: "Baltic Textiles OÜ", collection: "Summer Breeze", unitCost: 22, unitPrice: 85, reorderPoint: 70 },
  { sku: "SB-TP-002", productName: "Sunlit Smocked Blouse", currentStock: 45, incomingStock: 80, salesLast30Days: 36, daysRemaining: 38, dailySalesVelocity: 1.2, category: "normal", status: "low_stock", supplier: "Nordic Stitch AS", collection: "Summer Breeze", unitCost: 26, unitPrice: 98, reorderPoint: 50 },
  { sku: "SB-PT-001", productName: "Breeze Wide-Leg Trouser", currentStock: 132, incomingStock: 0, salesLast30Days: 85, daysRemaining: 47, dailySalesVelocity: 2.83, category: "fast", status: "in_stock", supplier: "Baltic Textiles OÜ", collection: "Summer Breeze", unitCost: 32, unitPrice: 120, reorderPoint: 65 },
  { sku: "SB-PT-002", productName: "Sunlit Linen Trouser", currentStock: 67, incomingStock: 0, salesLast30Days: 42, daysRemaining: 48, dailySalesVelocity: 1.4, category: "normal", status: "in_stock", supplier: "Nordic Stitch AS", collection: "Summer Breeze", unitCost: 34, unitPrice: 130, reorderPoint: 55 },
  { sku: "SB-SK-001", productName: "Breeze A-Line Midi Skirt", currentStock: 98, incomingStock: 50, salesLast30Days: 60, daysRemaining: 49, dailySalesVelocity: 2.0, category: "normal", status: "in_stock", supplier: "Baltic Textiles OÜ", collection: "Summer Breeze", unitCost: 28, unitPrice: 105, reorderPoint: 55 },
  { sku: "SB-SK-002", productName: "Sunlit Wrap Skirt", currentStock: 5, incomingStock: 0, salesLast30Days: 38, daysRemaining: 4, dailySalesVelocity: 1.27, category: "fast", status: "critical", supplier: "Nordic Stitch AS", collection: "Summer Breeze", unitCost: 24, unitPrice: 95, reorderPoint: 45 },
  { sku: "SB-JK-001", productName: "Breeze Cotton Blazer", currentStock: 54, incomingStock: 40, salesLast30Days: 28, daysRemaining: 58, dailySalesVelocity: 0.93, category: "normal", status: "in_stock", supplier: "Baltic Textiles OÜ", collection: "Summer Breeze", unitCost: 52, unitPrice: 195, reorderPoint: 40 },
  { sku: "SB-SH-001", productName: "Breeze Linen Shorts", currentStock: 72, incomingStock: 0, salesLast30Days: 55, daysRemaining: 39, dailySalesVelocity: 1.83, category: "normal", status: "in_stock", supplier: "Baltic Textiles OÜ", collection: "Summer Breeze", unitCost: 20, unitPrice: 78, reorderPoint: 50 },
  { sku: "SB-JR-001", productName: "Summer Breeze Jumpsuit", currentStock: 36, incomingStock: 60, salesLast30Days: 32, daysRemaining: 34, dailySalesVelocity: 1.07, category: "normal", status: "low_stock", supplier: "Nordic Stitch AS", collection: "Summer Breeze", unitCost: 46, unitPrice: 175, reorderPoint: 45 },
  { sku: "SB-AC-001", productName: "Breeze Woven Tote", currentStock: 114, incomingStock: 0, salesLast30Days: 68, daysRemaining: 50, dailySalesVelocity: 2.27, category: "fast", status: "in_stock", supplier: "Baltic Textiles OÜ", collection: "Summer Breeze", unitCost: 16, unitPrice: 62, reorderPoint: 55 },
  { sku: "SB-AC-002", productName: "Sunlit Straw Hat", currentStock: 0, incomingStock: 120, salesLast30Days: 44, daysRemaining: 0, dailySalesVelocity: 1.47, category: "fast", status: "out_of_stock", supplier: "Nordic Stitch AS", collection: "Summer Breeze", unitCost: 12, unitPrice: 48, reorderPoint: 50 },
  { sku: "SB-TP-003", productName: "Breeze Cropped Tank", currentStock: 188, incomingStock: 0, salesLast30Days: 112, daysRemaining: 50, dailySalesVelocity: 3.73, category: "fast", status: "in_stock", supplier: "Baltic Textiles OÜ", collection: "Summer Breeze", unitCost: 14, unitPrice: 55, reorderPoint: 80 },
  { sku: "SB-DR-004", productName: "Breeze Halter Sundress", currentStock: 64, incomingStock: 0, salesLast30Days: 40, daysRemaining: 48, dailySalesVelocity: 1.33, category: "normal", status: "in_stock", supplier: "Nordic Stitch AS", collection: "Summer Breeze", unitCost: 36, unitPrice: 135, reorderPoint: 50 },
  { sku: "SB-PT-003", productName: "Sunlit Cropped Pant", currentStock: 28, incomingStock: 0, salesLast30Days: 18, daysRemaining: 47, dailySalesVelocity: 0.6, category: "slow", status: "low_stock", supplier: "Baltic Textiles OÜ", collection: "Summer Breeze", unitCost: 30, unitPrice: 115, reorderPoint: 50 },
  { sku: "SB-SH-002", productName: "Breeze Denim Shorts", currentStock: 142, incomingStock: 100, salesLast30Days: 90, daysRemaining: 47, dailySalesVelocity: 3.0, category: "fast", status: "in_stock", supplier: "Nordic Stitch AS", collection: "Summer Breeze", unitCost: 24, unitPrice: 92, reorderPoint: 60 },
  { sku: "SB-JK-002", productName: "Sunlit Cropped Jacket", currentStock: 42, incomingStock: 0, salesLast30Days: 22, daysRemaining: 57, dailySalesVelocity: 0.73, category: "slow", status: "low_stock", supplier: "Baltic Textiles OÜ", collection: "Summer Breeze", unitCost: 48, unitPrice: 180, reorderPoint: 40 },
  { sku: "SB-DR-005", productName: "Sunlit Wrap Maxi Dress", currentStock: 0, incomingStock: 0, salesLast30Days: 52, daysRemaining: 0, dailySalesVelocity: 1.73, category: "fast", status: "out_of_stock", supplier: "Nordic Stitch AS", collection: "Summer Breeze", unitCost: 40, unitPrice: 160, reorderPoint: 55 },

  // ── Linen Luxe (LN) ────────────────────────────────────────────────
  { sku: "LN-DR-001", productName: "Linen Wrap Dress", currentStock: 173, incomingStock: 80, salesLast30Days: 130, daysRemaining: 40, dailySalesVelocity: 4.33, category: "fast", status: "in_stock", supplier: "Baltic Textiles OÜ", collection: "Linen Luxe", unitCost: 48, unitPrice: 190, reorderPoint: 80 },
  { sku: "LN-DR-002", productName: "Linen Maxi Dress", currentStock: 3, incomingStock: 150, salesLast30Days: 72, daysRemaining: 1, dailySalesVelocity: 2.4, category: "fast", status: "critical", supplier: "Linen House EU", collection: "Linen Luxe", unitCost: 52, unitPrice: 210, reorderPoint: 70 },
  { sku: "LN-DR-003", productName: "Luxe Slip Dress", currentStock: 94, incomingStock: 0, salesLast30Days: 58, daysRemaining: 49, dailySalesVelocity: 1.93, category: "normal", status: "in_stock", supplier: "Baltic Textiles OÜ", collection: "Linen Luxe", unitCost: 44, unitPrice: 175, reorderPoint: 55 },
  { sku: "LN-TP-001", productName: "Linen Button-Down Shirt", currentStock: 132, incomingStock: 0, salesLast30Days: 88, daysRemaining: 45, dailySalesVelocity: 2.93, category: "fast", status: "in_stock", supplier: "Linen House EU", collection: "Linen Luxe", unitCost: 30, unitPrice: 118, reorderPoint: 65 },
  { sku: "LN-TP-002", productName: "Luxe Linen Blouse", currentStock: 60, incomingStock: 60, salesLast30Days: 44, daysRemaining: 41, dailySalesVelocity: 1.47, category: "normal", status: "in_stock", supplier: "Baltic Textiles OÜ", collection: "Linen Luxe", unitCost: 34, unitPrice: 135, reorderPoint: 50 },
  { sku: "LN-PT-001", productName: "Linen Wide-Leg Pant", currentStock: 108, incomingStock: 100, salesLast30Days: 78, daysRemaining: 42, dailySalesVelocity: 2.6, category: "fast", status: "in_stock", supplier: "Linen House EU", collection: "Linen Luxe", unitCost: 36, unitPrice: 145, reorderPoint: 60 },
  { sku: "LN-PT-002", productName: "Luxe Tapered Trouser", currentStock: 48, incomingStock: 0, salesLast30Days: 34, daysRemaining: 42, dailySalesVelocity: 1.13, category: "normal", status: "low_stock", supplier: "Baltic Textiles OÜ", collection: "Linen Luxe", unitCost: 38, unitPrice: 155, reorderPoint: 50 },
  { sku: "LN-SK-001", productName: "Linen Midi Skirt", currentStock: 82, incomingStock: 0, salesLast30Days: 52, daysRemaining: 47, dailySalesVelocity: 1.73, category: "normal", status: "in_stock", supplier: "Linen House EU", collection: "Linen Luxe", unitCost: 28, unitPrice: 110, reorderPoint: 50 },
  { sku: "LN-JK-001", productName: "Linen Relaxed Blazer", currentStock: 38, incomingStock: 40, salesLast30Days: 24, daysRemaining: 48, dailySalesVelocity: 0.8, category: "slow", status: "low_stock", supplier: "Baltic Textiles OÜ", collection: "Linen Luxe", unitCost: 58, unitPrice: 230, reorderPoint: 40 },
  { sku: "LN-JR-001", productName: "Luxe Linen Jumpsuit", currentStock: 52, incomingStock: 0, salesLast30Days: 36, daysRemaining: 43, dailySalesVelocity: 1.2, category: "normal", status: "in_stock", supplier: "Linen House EU", collection: "Linen Luxe", unitCost: 50, unitPrice: 200, reorderPoint: 45 },
  { sku: "LN-SH-001", productName: "Linen Pleated Shorts", currentStock: 68, incomingStock: 80, salesLast30Days: 46, daysRemaining: 44, dailySalesVelocity: 1.53, category: "normal", status: "in_stock", supplier: "Baltic Textiles OÜ", collection: "Linen Luxe", unitCost: 22, unitPrice: 88, reorderPoint: 45 },
  { sku: "LN-AC-001", productName: "Luxe Linen Scarf", currentStock: 124, incomingStock: 0, salesLast30Days: 62, daysRemaining: 60, dailySalesVelocity: 2.07, category: "fast", status: "in_stock", supplier: "Linen House EU", collection: "Linen Luxe", unitCost: 14, unitPrice: 55, reorderPoint: 50 },
  { sku: "LN-DR-004", productName: "Linen Shirt Dress", currentStock: 82, incomingStock: 0, salesLast30Days: 48, daysRemaining: 51, dailySalesVelocity: 1.6, category: "normal", status: "in_stock", supplier: "Baltic Textiles OÜ", collection: "Linen Luxe", unitCost: 46, unitPrice: 185, reorderPoint: 55 },
  { sku: "LN-TP-003", productName: "Linen Sleeveless Top", currentStock: 110, incomingStock: 0, salesLast30Days: 74, daysRemaining: 45, dailySalesVelocity: 2.47, category: "fast", status: "in_stock", supplier: "Linen House EU", collection: "Linen Luxe", unitCost: 20, unitPrice: 78, reorderPoint: 55 },
  { sku: "LN-PT-003", productName: "Luxe Cropped Linen Pant", currentStock: 22, incomingStock: 50, salesLast30Days: 14, daysRemaining: 47, dailySalesVelocity: 0.47, category: "slow", status: "low_stock", supplier: "Baltic Textiles OÜ", collection: "Linen Luxe", unitCost: 32, unitPrice: 128, reorderPoint: 45 },
  { sku: "LN-SK-002", productName: "Luxe Pleated Skirt", currentStock: 58, incomingStock: 0, salesLast30Days: 32, daysRemaining: 54, dailySalesVelocity: 1.07, category: "normal", status: "in_stock", supplier: "Linen House EU", collection: "Linen Luxe", unitCost: 30, unitPrice: 120, reorderPoint: 45 },
  { sku: "LN-TP-004", productName: "Luxe Silk-Linen Top", currentStock: 48, incomingStock: 0, salesLast30Days: 30, daysRemaining: 48, dailySalesVelocity: 1.0, category: "normal", status: "low_stock", supplier: "Baltic Textiles OÜ", collection: "Linen Luxe", unitCost: 36, unitPrice: 142, reorderPoint: 45 },
  { sku: "LN-DR-005", productName: "Linen Tiered Sundress", currentStock: 0, incomingStock: 120, salesLast30Days: 56, daysRemaining: 0, dailySalesVelocity: 1.87, category: "fast", status: "out_of_stock", supplier: "Linen House EU", collection: "Linen Luxe", unitCost: 42, unitPrice: 165, reorderPoint: 55 },
  { sku: "LN-PT-004", productName: "Linen Drawstring Pant", currentStock: 92, incomingStock: 0, salesLast30Days: 54, daysRemaining: 51, dailySalesVelocity: 1.8, category: "normal", status: "in_stock", supplier: "Baltic Textiles OÜ", collection: "Linen Luxe", unitCost: 34, unitPrice: 135, reorderPoint: 50 },
  { sku: "LN-AC-002", productName: "Luxe Leather Belt", currentStock: 140, incomingStock: 0, salesLast30Days: 48, daysRemaining: 88, dailySalesVelocity: 1.6, category: "normal", status: "in_stock", supplier: "Linen House EU", collection: "Linen Luxe", unitCost: 18, unitPrice: 72, reorderPoint: 45 },

  // ── Evening Bloom (EB) ─────────────────────────────────────────────
  { sku: "EB-DR-001", productName: "Evening Bloom Maxi Gown", currentStock: 62, incomingStock: 50, salesLast30Days: 48, daysRemaining: 39, dailySalesVelocity: 1.6, category: "normal", status: "in_stock", supplier: "Nordic Stitch AS", collection: "Evening Bloom", unitCost: 58, unitPrice: 240, reorderPoint: 50 },
  { sku: "EB-DR-002", productName: "Bloom Midi Cocktail Dress", currentStock: 48, incomingStock: 0, salesLast30Days: 40, daysRemaining: 36, dailySalesVelocity: 1.33, category: "normal", status: "low_stock", supplier: "Atelier Tallinn", collection: "Evening Bloom", unitCost: 52, unitPrice: 210, reorderPoint: 50 },
  { sku: "EB-DR-003", productName: "Noir Satin Slip Dress", currentStock: 82, incomingStock: 0, salesLast30Days: 62, daysRemaining: 40, dailySalesVelocity: 2.07, category: "fast", status: "in_stock", supplier: "Nordic Stitch AS", collection: "Evening Bloom", unitCost: 44, unitPrice: 180, reorderPoint: 55 },
  { sku: "EB-TP-001", productName: "Bloom Silk Camisole", currentStock: 98, incomingStock: 60, salesLast30Days: 72, daysRemaining: 41, dailySalesVelocity: 2.4, category: "fast", status: "in_stock", supplier: "Atelier Tallinn", collection: "Evening Bloom", unitCost: 32, unitPrice: 128, reorderPoint: 55 },
  { sku: "EB-TP-002", productName: "Noir Lace Bodysuit", currentStock: 34, incomingStock: 40, salesLast30Days: 28, daysRemaining: 36, dailySalesVelocity: 0.93, category: "normal", status: "low_stock", supplier: "Nordic Stitch AS", collection: "Evening Bloom", unitCost: 38, unitPrice: 150, reorderPoint: 40 },
  { sku: "EB-PT-001", productName: "Bloom Wide-Leg Trouser", currentStock: 56, incomingStock: 0, salesLast30Days: 36, daysRemaining: 47, dailySalesVelocity: 1.2, category: "normal", status: "in_stock", supplier: "Atelier Tallinn", collection: "Evening Bloom", unitCost: 42, unitPrice: 170, reorderPoint: 45 },
  { sku: "EB-SK-001", productName: "Bloom Sequin Midi Skirt", currentStock: 42, incomingStock: 0, salesLast30Days: 30, daysRemaining: 42, dailySalesVelocity: 1.0, category: "normal", status: "low_stock", supplier: "Nordic Stitch AS", collection: "Evening Bloom", unitCost: 36, unitPrice: 145, reorderPoint: 40 },
  { sku: "EB-JK-001", productName: "Noir Tailored Blazer", currentStock: 38, incomingStock: 0, salesLast30Days: 22, daysRemaining: 52, dailySalesVelocity: 0.73, category: "slow", status: "low_stock", supplier: "Atelier Tallinn", collection: "Evening Bloom", unitCost: 62, unitPrice: 260, reorderPoint: 35 },
  { sku: "EB-JR-001", productName: "Bloom Evening Jumpsuit", currentStock: 44, incomingStock: 50, salesLast30Days: 34, daysRemaining: 39, dailySalesVelocity: 1.13, category: "normal", status: "in_stock", supplier: "Nordic Stitch AS", collection: "Evening Bloom", unitCost: 54, unitPrice: 220, reorderPoint: 45 },
  { sku: "EB-AC-001", productName: "Noir Crystal Earrings", currentStock: 74, incomingStock: 100, salesLast30Days: 56, daysRemaining: 40, dailySalesVelocity: 1.87, category: "normal", status: "in_stock", supplier: "Atelier Tallinn", collection: "Evening Bloom", unitCost: 10, unitPrice: 42, reorderPoint: 50 },
  { sku: "EB-AC-002", productName: "Bloom Velvet Clutch", currentStock: 52, incomingStock: 0, salesLast30Days: 38, daysRemaining: 41, dailySalesVelocity: 1.27, category: "normal", status: "in_stock", supplier: "Nordic Stitch AS", collection: "Evening Bloom", unitCost: 22, unitPrice: 88, reorderPoint: 40 },
  { sku: "EB-DR-004", productName: "Bloom Strapless Gown", currentStock: 2, incomingStock: 80, salesLast30Days: 36, daysRemaining: 2, dailySalesVelocity: 1.2, category: "fast", status: "critical", supplier: "Atelier Tallinn", collection: "Evening Bloom", unitCost: 60, unitPrice: 250, reorderPoint: 40 },
  { sku: "EB-TP-003", productName: "Noir Silk Wrap Top", currentStock: 64, incomingStock: 0, salesLast30Days: 44, daysRemaining: 44, dailySalesVelocity: 1.47, category: "normal", status: "in_stock", supplier: "Nordic Stitch AS", collection: "Evening Bloom", unitCost: 34, unitPrice: 138, reorderPoint: 45 },
  { sku: "EB-PT-002", productName: "Noir Palazzo Pant", currentStock: 28, incomingStock: 60, salesLast30Days: 20, daysRemaining: 42, dailySalesVelocity: 0.67, category: "slow", status: "low_stock", supplier: "Atelier Tallinn", collection: "Evening Bloom", unitCost: 40, unitPrice: 165, reorderPoint: 40 },
  { sku: "EB-SK-002", productName: "Bloom Satin Pencil Skirt", currentStock: 66, incomingStock: 0, salesLast30Days: 42, daysRemaining: 47, dailySalesVelocity: 1.4, category: "normal", status: "in_stock", supplier: "Nordic Stitch AS", collection: "Evening Bloom", unitCost: 32, unitPrice: 130, reorderPoint: 45 },
  { sku: "EB-TP-004", productName: "Blossom Embroidered Top", currentStock: 46, incomingStock: 0, salesLast30Days: 26, daysRemaining: 53, dailySalesVelocity: 0.87, category: "slow", status: "low_stock", supplier: "Atelier Tallinn", collection: "Evening Bloom", unitCost: 40, unitPrice: 160, reorderPoint: 40 },
  { sku: "EB-DR-005", productName: "Noir One-Shoulder Dress", currentStock: 0, incomingStock: 100, salesLast30Days: 42, daysRemaining: 0, dailySalesVelocity: 1.4, category: "fast", status: "out_of_stock", supplier: "Nordic Stitch AS", collection: "Evening Bloom", unitCost: 50, unitPrice: 205, reorderPoint: 45 },
  { sku: "EB-AC-003", productName: "Bloom Pearl Necklace", currentStock: 86, incomingStock: 60, salesLast30Days: 52, daysRemaining: 50, dailySalesVelocity: 1.73, category: "normal", status: "in_stock", supplier: "Atelier Tallinn", collection: "Evening Bloom", unitCost: 16, unitPrice: 65, reorderPoint: 50 },
  { sku: "EB-JK-002", productName: "Noir Cape Blazer", currentStock: 18, incomingStock: 0, salesLast30Days: 14, daysRemaining: 39, dailySalesVelocity: 0.47, category: "slow", status: "low_stock", supplier: "Nordic Stitch AS", collection: "Evening Bloom", unitCost: 68, unitPrice: 280, reorderPoint: 30 },
  { sku: "EB-JR-002", productName: "Bloom Romper", currentStock: 56, incomingStock: 40, salesLast30Days: 38, daysRemaining: 44, dailySalesVelocity: 1.27, category: "normal", status: "in_stock", supplier: "Atelier Tallinn", collection: "Evening Bloom", unitCost: 48, unitPrice: 195, reorderPoint: 45 },

  // ── Urban Edge (UE) ────────────────────────────────────────────────
  { sku: "UE-JK-001", productName: "Urban Edge Leather Jacket", currentStock: 48, incomingStock: 40, salesLast30Days: 36, daysRemaining: 40, dailySalesVelocity: 1.2, category: "normal", status: "low_stock", supplier: "Urban Craft OÜ", collection: "Urban Edge", unitCost: 72, unitPrice: 290, reorderPoint: 40 },
  { sku: "UE-JK-002", productName: "Edge Denim Trucker Jacket", currentStock: 64, incomingStock: 0, salesLast30Days: 48, daysRemaining: 40, dailySalesVelocity: 1.6, category: "normal", status: "in_stock", supplier: "Urban Craft OÜ", collection: "Urban Edge", unitCost: 48, unitPrice: 195, reorderPoint: 50 },
  { sku: "UE-PT-001", productName: "Edge Cargo Pant", currentStock: 96, incomingStock: 80, salesLast30Days: 72, daysRemaining: 40, dailySalesVelocity: 2.4, category: "fast", status: "in_stock", supplier: "Urban Craft OÜ", collection: "Urban Edge", unitCost: 34, unitPrice: 135, reorderPoint: 55 },
  { sku: "UE-PT-002", productName: "Urban Slim Fit Jeans", currentStock: 124, incomingStock: 0, salesLast30Days: 88, daysRemaining: 42, dailySalesVelocity: 2.93, category: "fast", status: "in_stock", supplier: "Denim House LV", collection: "Urban Edge", unitCost: 28, unitPrice: 115, reorderPoint: 65 },
  { sku: "UE-TP-001", productName: "Edge Graphic Tee", currentStock: 178, incomingStock: 0, salesLast30Days: 120, daysRemaining: 45, dailySalesVelocity: 4.0, category: "fast", status: "in_stock", supplier: "Urban Craft OÜ", collection: "Urban Edge", unitCost: 12, unitPrice: 48, reorderPoint: 80 },
  { sku: "UE-TP-002", productName: "Urban Oversized Hoodie", currentStock: 82, incomingStock: 100, salesLast30Days: 58, daysRemaining: 42, dailySalesVelocity: 1.93, category: "normal", status: "in_stock", supplier: "Denim House LV", collection: "Urban Edge", unitCost: 26, unitPrice: 105, reorderPoint: 55 },
  { sku: "UE-DR-001", productName: "Edge Ribbed Bodycon Dress", currentStock: 44, incomingStock: 60, salesLast30Days: 38, daysRemaining: 35, dailySalesVelocity: 1.27, category: "normal", status: "low_stock", supplier: "Urban Craft OÜ", collection: "Urban Edge", unitCost: 30, unitPrice: 125, reorderPoint: 45 },
  { sku: "UE-SK-001", productName: "Urban Faux Leather Skirt", currentStock: 52, incomingStock: 0, salesLast30Days: 36, daysRemaining: 43, dailySalesVelocity: 1.2, category: "normal", status: "in_stock", supplier: "Urban Craft OÜ", collection: "Urban Edge", unitCost: 28, unitPrice: 115, reorderPoint: 40 },
  { sku: "UE-SH-001", productName: "Edge Distressed Shorts", currentStock: 76, incomingStock: 0, salesLast30Days: 52, daysRemaining: 44, dailySalesVelocity: 1.73, category: "normal", status: "in_stock", supplier: "Denim House LV", collection: "Urban Edge", unitCost: 18, unitPrice: 72, reorderPoint: 45 },
  { sku: "UE-AC-001", productName: "Edge Canvas Backpack", currentStock: 58, incomingStock: 50, salesLast30Days: 42, daysRemaining: 41, dailySalesVelocity: 1.4, category: "normal", status: "in_stock", supplier: "Urban Craft OÜ", collection: "Urban Edge", unitCost: 24, unitPrice: 95, reorderPoint: 45 },
  { sku: "UE-JR-001", productName: "Urban Utility Jumpsuit", currentStock: 34, incomingStock: 0, salesLast30Days: 24, daysRemaining: 43, dailySalesVelocity: 0.8, category: "slow", status: "low_stock", supplier: "Urban Craft OÜ", collection: "Urban Edge", unitCost: 42, unitPrice: 170, reorderPoint: 40 },
  { sku: "UE-TP-003", productName: "Edge Cropped Hoodie", currentStock: 68, incomingStock: 0, salesLast30Days: 44, daysRemaining: 46, dailySalesVelocity: 1.47, category: "normal", status: "in_stock", supplier: "Denim House LV", collection: "Urban Edge", unitCost: 22, unitPrice: 88, reorderPoint: 45 },
  { sku: "UE-PT-003", productName: "Edge Parachute Pant", currentStock: 42, incomingStock: 50, salesLast30Days: 32, daysRemaining: 39, dailySalesVelocity: 1.07, category: "normal", status: "low_stock", supplier: "Urban Craft OÜ", collection: "Urban Edge", unitCost: 36, unitPrice: 148, reorderPoint: 45 },
  { sku: "UE-JK-003", productName: "Urban Bomber Jacket", currentStock: 28, incomingStock: 0, salesLast30Days: 20, daysRemaining: 42, dailySalesVelocity: 0.67, category: "slow", status: "low_stock", supplier: "Denim House LV", collection: "Urban Edge", unitCost: 55, unitPrice: 225, reorderPoint: 35 },
  { sku: "UE-AC-002", productName: "Edge Metal Sunglasses", currentStock: 112, incomingStock: 0, salesLast30Days: 64, daysRemaining: 53, dailySalesVelocity: 2.13, category: "fast", status: "in_stock", supplier: "Urban Craft OÜ", collection: "Urban Edge", unitCost: 8, unitPrice: 35, reorderPoint: 55 },
  { sku: "UE-TP-004", productName: "Urban Street Tee", currentStock: 190, incomingStock: 0, salesLast30Days: 108, daysRemaining: 53, dailySalesVelocity: 3.6, category: "fast", status: "in_stock", supplier: "Denim House LV", collection: "Urban Edge", unitCost: 10, unitPrice: 42, reorderPoint: 75 },
  { sku: "UE-DR-002", productName: "Edge Knit Mini Dress", currentStock: 36, incomingStock: 40, salesLast30Days: 28, daysRemaining: 39, dailySalesVelocity: 0.93, category: "normal", status: "low_stock", supplier: "Urban Craft OÜ", collection: "Urban Edge", unitCost: 32, unitPrice: 130, reorderPoint: 40 },
  { sku: "UE-PT-004", productName: "Urban Relaxed Jogger", currentStock: 88, incomingStock: 0, salesLast30Days: 56, daysRemaining: 47, dailySalesVelocity: 1.87, category: "normal", status: "in_stock", supplier: "Denim House LV", collection: "Urban Edge", unitCost: 24, unitPrice: 98, reorderPoint: 50 },
  { sku: "UE-SH-002", productName: "Edge Bike Shorts", currentStock: 0, incomingStock: 100, salesLast30Days: 44, daysRemaining: 0, dailySalesVelocity: 1.47, category: "fast", status: "out_of_stock", supplier: "Urban Craft OÜ", collection: "Urban Edge", unitCost: 14, unitPrice: 55, reorderPoint: 45 },
  { sku: "UE-AC-003", productName: "Urban Beanie", currentStock: 144, incomingStock: 0, salesLast30Days: 34, daysRemaining: 127, dailySalesVelocity: 1.13, category: "slow", status: "in_stock", supplier: "Denim House LV", collection: "Urban Edge", unitCost: 8, unitPrice: 32, reorderPoint: 40 },

  // ── Boho Spirit (BH) ───────────────────────────────────────────────
  { sku: "BH-TP-001", productName: "Boho Embroidered Blouse", currentStock: 96, incomingStock: 60, salesLast30Days: 82, daysRemaining: 35, dailySalesVelocity: 2.73, category: "fast", status: "in_stock", supplier: "Artisan Weave EE", collection: "Boho Spirit", unitCost: 28, unitPrice: 115, reorderPoint: 60 },
  { sku: "BH-TP-002", productName: "Spirit Fringed Crop Top", currentStock: 48, incomingStock: 0, salesLast30Days: 36, daysRemaining: 40, dailySalesVelocity: 1.2, category: "normal", status: "low_stock", supplier: "Artisan Weave EE", collection: "Boho Spirit", unitCost: 22, unitPrice: 88, reorderPoint: 45 },
  { sku: "BH-TP-003", productName: "Boho Peasant Top", currentStock: 148, incomingStock: 0, salesLast30Days: 110, daysRemaining: 40, dailySalesVelocity: 3.67, category: "fast", status: "in_stock", supplier: "Artisan Weave EE", collection: "Boho Spirit", unitCost: 24, unitPrice: 95, reorderPoint: 70 },
  { sku: "BH-DR-001", productName: "Spirit Maxi Dress", currentStock: 72, incomingStock: 80, salesLast30Days: 62, daysRemaining: 35, dailySalesVelocity: 2.07, category: "fast", status: "in_stock", supplier: "Artisan Weave EE", collection: "Boho Spirit", unitCost: 38, unitPrice: 155, reorderPoint: 55 },
  { sku: "BH-DR-002", productName: "Boho Tiered Sundress", currentStock: 2, incomingStock: 100, salesLast30Days: 56, daysRemaining: 1, dailySalesVelocity: 1.87, category: "fast", status: "critical", supplier: "Artisan Weave EE", collection: "Boho Spirit", unitCost: 36, unitPrice: 145, reorderPoint: 55 },
  { sku: "BH-PT-001", productName: "Spirit Palazzo Pant", currentStock: 86, incomingStock: 0, salesLast30Days: 58, daysRemaining: 44, dailySalesVelocity: 1.93, category: "normal", status: "in_stock", supplier: "Artisan Weave EE", collection: "Boho Spirit", unitCost: 30, unitPrice: 125, reorderPoint: 50 },
  { sku: "BH-PT-002", productName: "Boho Flared Jean", currentStock: 56, incomingStock: 60, salesLast30Days: 42, daysRemaining: 40, dailySalesVelocity: 1.4, category: "normal", status: "in_stock", supplier: "Artisan Weave EE", collection: "Boho Spirit", unitCost: 32, unitPrice: 130, reorderPoint: 45 },
  { sku: "BH-SK-001", productName: "Spirit Patchwork Skirt", currentStock: 44, incomingStock: 0, salesLast30Days: 34, daysRemaining: 39, dailySalesVelocity: 1.13, category: "normal", status: "low_stock", supplier: "Artisan Weave EE", collection: "Boho Spirit", unitCost: 26, unitPrice: 108, reorderPoint: 40 },
  { sku: "BH-JK-001", productName: "Boho Fringed Kimono", currentStock: 68, incomingStock: 0, salesLast30Days: 44, daysRemaining: 46, dailySalesVelocity: 1.47, category: "normal", status: "in_stock", supplier: "Artisan Weave EE", collection: "Boho Spirit", unitCost: 34, unitPrice: 140, reorderPoint: 45 },
  { sku: "BH-JR-001", productName: "Spirit Boho Jumpsuit", currentStock: 38, incomingStock: 40, salesLast30Days: 30, daysRemaining: 38, dailySalesVelocity: 1.0, category: "normal", status: "low_stock", supplier: "Artisan Weave EE", collection: "Boho Spirit", unitCost: 42, unitPrice: 175, reorderPoint: 40 },
  { sku: "BH-AC-001", productName: "Spirit Tassel Earrings", currentStock: 98, incomingStock: 0, salesLast30Days: 68, daysRemaining: 43, dailySalesVelocity: 2.27, category: "fast", status: "in_stock", supplier: "Artisan Weave EE", collection: "Boho Spirit", unitCost: 8, unitPrice: 34, reorderPoint: 50 },
  { sku: "BH-AC-002", productName: "Boho Beaded Necklace", currentStock: 76, incomingStock: 50, salesLast30Days: 52, daysRemaining: 44, dailySalesVelocity: 1.73, category: "normal", status: "in_stock", supplier: "Artisan Weave EE", collection: "Boho Spirit", unitCost: 10, unitPrice: 42, reorderPoint: 45 },
  { sku: "BH-TP-004", productName: "Spirit Crochet Tank", currentStock: 62, incomingStock: 0, salesLast30Days: 48, daysRemaining: 39, dailySalesVelocity: 1.6, category: "normal", status: "in_stock", supplier: "Artisan Weave EE", collection: "Boho Spirit", unitCost: 18, unitPrice: 72, reorderPoint: 45 },
  { sku: "BH-DR-003", productName: "Boho Lace Insert Dress", currentStock: 54, incomingStock: 0, salesLast30Days: 38, daysRemaining: 43, dailySalesVelocity: 1.27, category: "normal", status: "in_stock", supplier: "Artisan Weave EE", collection: "Boho Spirit", unitCost: 34, unitPrice: 138, reorderPoint: 45 },
  { sku: "BH-SK-002", productName: "Spirit Embroidered Midi", currentStock: 32, incomingStock: 50, salesLast30Days: 26, daysRemaining: 37, dailySalesVelocity: 0.87, category: "slow", status: "low_stock", supplier: "Artisan Weave EE", collection: "Boho Spirit", unitCost: 30, unitPrice: 122, reorderPoint: 40 },
  { sku: "BH-AC-003", productName: "Boho Woven Belt", currentStock: 110, incomingStock: 0, salesLast30Days: 42, daysRemaining: 79, dailySalesVelocity: 1.4, category: "normal", status: "in_stock", supplier: "Artisan Weave EE", collection: "Boho Spirit", unitCost: 12, unitPrice: 48, reorderPoint: 40 },
  { sku: "BH-SH-001", productName: "Spirit Embroidered Shorts", currentStock: 58, incomingStock: 0, salesLast30Days: 44, daysRemaining: 40, dailySalesVelocity: 1.47, category: "normal", status: "in_stock", supplier: "Artisan Weave EE", collection: "Boho Spirit", unitCost: 20, unitPrice: 82, reorderPoint: 40 },
  { sku: "BH-TP-005", productName: "Boho Patterned Kimono Top", currentStock: 42, incomingStock: 0, salesLast30Days: 28, daysRemaining: 45, dailySalesVelocity: 0.93, category: "slow", status: "low_stock", supplier: "Artisan Weave EE", collection: "Boho Spirit", unitCost: 26, unitPrice: 105, reorderPoint: 40 },
  { sku: "BH-DR-004", productName: "Spirit Off-Shoulder Dress", currentStock: 0, incomingStock: 120, salesLast30Days: 48, daysRemaining: 0, dailySalesVelocity: 1.6, category: "fast", status: "out_of_stock", supplier: "Artisan Weave EE", collection: "Boho Spirit", unitCost: 40, unitPrice: 162, reorderPoint: 50 },
  { sku: "BH-AC-004", productName: "Spirit Headband Set", currentStock: 88, incomingStock: 0, salesLast30Days: 36, daysRemaining: 73, dailySalesVelocity: 1.2, category: "normal", status: "in_stock", supplier: "Artisan Weave EE", collection: "Boho Spirit", unitCost: 6, unitPrice: 24, reorderPoint: 40 },

  // ── Classic Core (CC) ──────────────────────────────────────────────
  { sku: "CC-TP-001", productName: "Classic Silk Blouse", currentStock: 142, incomingStock: 80, salesLast30Days: 108, daysRemaining: 39, dailySalesVelocity: 3.6, category: "fast", status: "in_stock", supplier: "Baltic Textiles OÜ", collection: "Classic Core", unitCost: 36, unitPrice: 145, reorderPoint: 70 },
  { sku: "CC-DR-001", productName: "Classic Sheath Dress", currentStock: 94, incomingStock: 0, salesLast30Days: 66, daysRemaining: 43, dailySalesVelocity: 2.2, category: "fast", status: "in_stock", supplier: "Baltic Textiles OÜ", collection: "Classic Core", unitCost: 42, unitPrice: 170, reorderPoint: 60 },
  { sku: "CC-JK-001", productName: "Classic Tailored Blazer", currentStock: 58, incomingStock: 40, salesLast30Days: 38, daysRemaining: 46, dailySalesVelocity: 1.27, category: "normal", status: "in_stock", supplier: "Tailor House OÜ", collection: "Classic Core", unitCost: 64, unitPrice: 260, reorderPoint: 45 },
  { sku: "CC-PT-001", productName: "Classic Straight Trouser", currentStock: 116, incomingStock: 0, salesLast30Days: 82, daysRemaining: 42, dailySalesVelocity: 2.73, category: "fast", status: "in_stock", supplier: "Baltic Textiles OÜ", collection: "Classic Core", unitCost: 34, unitPrice: 138, reorderPoint: 60 },
  { sku: "CC-SK-001", productName: "Classic A-Line Skirt", currentStock: 78, incomingStock: 60, salesLast30Days: 54, daysRemaining: 43, dailySalesVelocity: 1.8, category: "normal", status: "in_stock", supplier: "Tailor House OÜ", collection: "Classic Core", unitCost: 28, unitPrice: 115, reorderPoint: 50 },
  { sku: "CC-TP-002", productName: "Classic Cashmere Sweater", currentStock: 62, incomingStock: 100, salesLast30Days: 44, daysRemaining: 42, dailySalesVelocity: 1.47, category: "normal", status: "in_stock", supplier: "Baltic Textiles OÜ", collection: "Classic Core", unitCost: 52, unitPrice: 210, reorderPoint: 50 },
  { sku: "CC-DR-002", productName: "Classic Wrap Dress", currentStock: 82, incomingStock: 0, salesLast30Days: 58, daysRemaining: 42, dailySalesVelocity: 1.93, category: "normal", status: "in_stock", supplier: "Tailor House OÜ", collection: "Classic Core", unitCost: 40, unitPrice: 162, reorderPoint: 55 },
  { sku: "CC-BL-001", productName: "Classic Poplin Shirt", currentStock: 188, incomingStock: 0, salesLast30Days: 124, daysRemaining: 45, dailySalesVelocity: 4.13, category: "fast", status: "in_stock", supplier: "Baltic Textiles OÜ", collection: "Classic Core", unitCost: 22, unitPrice: 88, reorderPoint: 80 },
  { sku: "CC-PT-002", productName: "Classic Ankle Pant", currentStock: 64, incomingStock: 0, salesLast30Days: 46, daysRemaining: 42, dailySalesVelocity: 1.53, category: "normal", status: "in_stock", supplier: "Tailor House OÜ", collection: "Classic Core", unitCost: 30, unitPrice: 125, reorderPoint: 50 },
  { sku: "CC-JK-002", productName: "Classic Trench Coat", currentStock: 42, incomingStock: 0, salesLast30Days: 28, daysRemaining: 45, dailySalesVelocity: 0.93, category: "slow", status: "low_stock", supplier: "Baltic Textiles OÜ", collection: "Classic Core", unitCost: 68, unitPrice: 280, reorderPoint: 40 },
  { sku: "CC-AC-001", productName: "Classic Silk Scarf", currentStock: 134, incomingStock: 0, salesLast30Days: 72, daysRemaining: 56, dailySalesVelocity: 2.4, category: "fast", status: "in_stock", supplier: "Tailor House OÜ", collection: "Classic Core", unitCost: 16, unitPrice: 65, reorderPoint: 50 },
  { sku: "CC-TP-003", productName: "Classic Breton Stripe Top", currentStock: 106, incomingStock: 0, salesLast30Days: 68, daysRemaining: 47, dailySalesVelocity: 2.27, category: "fast", status: "in_stock", supplier: "Baltic Textiles OÜ", collection: "Classic Core", unitCost: 18, unitPrice: 72, reorderPoint: 55 },
  { sku: "CC-DR-003", productName: "Classic Shirt Dress", currentStock: 48, incomingStock: 50, salesLast30Days: 34, daysRemaining: 42, dailySalesVelocity: 1.13, category: "normal", status: "low_stock", supplier: "Tailor House OÜ", collection: "Classic Core", unitCost: 38, unitPrice: 155, reorderPoint: 45 },
  { sku: "CC-PT-003", productName: "Classic Wide-Leg Slacks", currentStock: 36, incomingStock: 0, salesLast30Days: 24, daysRemaining: 45, dailySalesVelocity: 0.8, category: "slow", status: "low_stock", supplier: "Baltic Textiles OÜ", collection: "Classic Core", unitCost: 40, unitPrice: 162, reorderPoint: 45 },
  { sku: "CC-SK-002", productName: "Classic Pencil Skirt", currentStock: 68, incomingStock: 0, salesLast30Days: 48, daysRemaining: 43, dailySalesVelocity: 1.6, category: "normal", status: "in_stock", supplier: "Tailor House OÜ", collection: "Classic Core", unitCost: 26, unitPrice: 108, reorderPoint: 45 },
  { sku: "CC-AC-002", productName: "Classic Leather Belt", currentStock: 120, incomingStock: 0, salesLast30Days: 56, daysRemaining: 64, dailySalesVelocity: 1.87, category: "normal", status: "in_stock", supplier: "Baltic Textiles OÜ", collection: "Classic Core", unitCost: 14, unitPrice: 58, reorderPoint: 45 },
  { sku: "CC-JR-001", productName: "Classic Crepe Jumpsuit", currentStock: 34, incomingStock: 40, salesLast30Days: 26, daysRemaining: 39, dailySalesVelocity: 0.87, category: "slow", status: "low_stock", supplier: "Tailor House OÜ", collection: "Classic Core", unitCost: 44, unitPrice: 180, reorderPoint: 40 },
  { sku: "CC-TP-004", productName: "Classic Merino Turtleneck", currentStock: 76, incomingStock: 80, salesLast30Days: 42, daysRemaining: 54, dailySalesVelocity: 1.4, category: "normal", status: "in_stock", supplier: "Baltic Textiles OÜ", collection: "Classic Core", unitCost: 38, unitPrice: 152, reorderPoint: 50 },
  { sku: "CC-DR-004", productName: "Classic Fit-and-Flare Dress", currentStock: 56, incomingStock: 0, salesLast30Days: 40, daysRemaining: 42, dailySalesVelocity: 1.33, category: "normal", status: "in_stock", supplier: "Tailor House OÜ", collection: "Classic Core", unitCost: 46, unitPrice: 188, reorderPoint: 45 },
  { sku: "CC-AC-003", productName: "Classic Pearl Studs", currentStock: 156, incomingStock: 0, salesLast30Days: 78, daysRemaining: 60, dailySalesVelocity: 2.6, category: "fast", status: "in_stock", supplier: "Baltic Textiles OÜ", collection: "Classic Core", unitCost: 8, unitPrice: 34, reorderPoint: 50 },

  // ── Coastal Charm (CT) ─────────────────────────────────────────────
  { sku: "CT-DR-001", productName: "Coastal Linen Sundress", currentStock: 88, incomingStock: 100, salesLast30Days: 72, daysRemaining: 37, dailySalesVelocity: 2.4, category: "fast", status: "in_stock", supplier: "Linen House EU", collection: "Coastal Charm", unitCost: 34, unitPrice: 138, reorderPoint: 60 },
  { sku: "CT-PT-001", productName: "Coastal Wide-Leg Trouser", currentStock: 96, incomingStock: 0, salesLast30Days: 72, daysRemaining: 40, dailySalesVelocity: 2.4, category: "fast", status: "in_stock", supplier: "Linen House EU", collection: "Coastal Charm", unitCost: 32, unitPrice: 128, reorderPoint: 55 },
  { sku: "CT-PT-002", productName: "Coastal Linen Trouser", currentStock: 168, incomingStock: 100, salesLast30Days: 124, daysRemaining: 41, dailySalesVelocity: 4.13, category: "fast", status: "in_stock", supplier: "Linen House EU", collection: "Coastal Charm", unitCost: 36, unitPrice: 145, reorderPoint: 70 },
  { sku: "CT-TP-001", productName: "Coastal Striped Blouse", currentStock: 112, incomingStock: 0, salesLast30Days: 78, daysRemaining: 43, dailySalesVelocity: 2.6, category: "fast", status: "in_stock", supplier: "Nordic Stitch AS", collection: "Coastal Charm", unitCost: 26, unitPrice: 105, reorderPoint: 55 },
  { sku: "CT-TP-002", productName: "Coastal Embroidered Top", currentStock: 60, incomingStock: 0, salesLast30Days: 48, daysRemaining: 38, dailySalesVelocity: 1.6, category: "normal", status: "in_stock", supplier: "Linen House EU", collection: "Coastal Charm", unitCost: 28, unitPrice: 112, reorderPoint: 45 },
  { sku: "CT-DR-002", productName: "Coastal Maxi Dress", currentStock: 4, incomingStock: 80, salesLast30Days: 58, daysRemaining: 2, dailySalesVelocity: 1.93, category: "fast", status: "critical", supplier: "Nordic Stitch AS", collection: "Coastal Charm", unitCost: 40, unitPrice: 165, reorderPoint: 55 },
  { sku: "CT-SK-001", productName: "Coastal Wrap Skirt", currentStock: 72, incomingStock: 50, salesLast30Days: 52, daysRemaining: 42, dailySalesVelocity: 1.73, category: "normal", status: "in_stock", supplier: "Linen House EU", collection: "Coastal Charm", unitCost: 24, unitPrice: 98, reorderPoint: 45 },
  { sku: "CT-SH-001", productName: "Coastal Linen Shorts", currentStock: 84, incomingStock: 0, salesLast30Days: 62, daysRemaining: 41, dailySalesVelocity: 2.07, category: "fast", status: "in_stock", supplier: "Nordic Stitch AS", collection: "Coastal Charm", unitCost: 20, unitPrice: 82, reorderPoint: 50 },
  { sku: "CT-JK-001", productName: "Coastal Lightweight Jacket", currentStock: 44, incomingStock: 0, salesLast30Days: 32, daysRemaining: 41, dailySalesVelocity: 1.07, category: "normal", status: "low_stock", supplier: "Linen House EU", collection: "Coastal Charm", unitCost: 48, unitPrice: 195, reorderPoint: 40 },
  { sku: "CT-JR-001", productName: "Coastal Romper", currentStock: 52, incomingStock: 60, salesLast30Days: 40, daysRemaining: 39, dailySalesVelocity: 1.33, category: "normal", status: "in_stock", supplier: "Nordic Stitch AS", collection: "Coastal Charm", unitCost: 38, unitPrice: 155, reorderPoint: 45 },
  { sku: "CT-AC-001", productName: "Coastal Woven Bag", currentStock: 92, incomingStock: 0, salesLast30Days: 64, daysRemaining: 43, dailySalesVelocity: 2.13, category: "fast", status: "in_stock", supplier: "Linen House EU", collection: "Coastal Charm", unitCost: 18, unitPrice: 72, reorderPoint: 50 },
  { sku: "CT-AC-002", productName: "Coastal Shell Necklace", currentStock: 124, incomingStock: 100, salesLast30Days: 68, daysRemaining: 55, dailySalesVelocity: 2.27, category: "fast", status: "in_stock", supplier: "Nordic Stitch AS", collection: "Coastal Charm", unitCost: 8, unitPrice: 34, reorderPoint: 50 },
  { sku: "CT-DR-003", productName: "Coastal Slip Dress", currentStock: 46, incomingStock: 0, salesLast30Days: 34, daysRemaining: 41, dailySalesVelocity: 1.13, category: "normal", status: "low_stock", supplier: "Linen House EU", collection: "Coastal Charm", unitCost: 32, unitPrice: 128, reorderPoint: 45 },
  { sku: "CT-TP-003", productName: "Coastal Crochet Top", currentStock: 38, incomingStock: 0, salesLast30Days: 30, daysRemaining: 38, dailySalesVelocity: 1.0, category: "normal", status: "low_stock", supplier: "Nordic Stitch AS", collection: "Coastal Charm", unitCost: 22, unitPrice: 88, reorderPoint: 40 },
  { sku: "CT-PT-003", productName: "Coastal Capri Pant", currentStock: 22, incomingStock: 50, salesLast30Days: 16, daysRemaining: 41, dailySalesVelocity: 0.53, category: "slow", status: "low_stock", supplier: "Linen House EU", collection: "Coastal Charm", unitCost: 28, unitPrice: 115, reorderPoint: 45 },
  { sku: "CT-SH-002", productName: "Coastal Board Shorts", currentStock: 98, incomingStock: 0, salesLast30Days: 42, daysRemaining: 70, dailySalesVelocity: 1.4, category: "normal", status: "in_stock", supplier: "Nordic Stitch AS", collection: "Coastal Charm", unitCost: 16, unitPrice: 65, reorderPoint: 45 },
  { sku: "CT-AC-003", productName: "Coastal Sun Hat", currentStock: 66, incomingStock: 0, salesLast30Days: 48, daysRemaining: 41, dailySalesVelocity: 1.6, category: "normal", status: "in_stock", supplier: "Linen House EU", collection: "Coastal Charm", unitCost: 14, unitPrice: 55, reorderPoint: 45 },
  { sku: "CT-DR-004", productName: "Coastal Tie-Dye Dress", currentStock: 0, incomingStock: 120, salesLast30Days: 44, daysRemaining: 0, dailySalesVelocity: 1.47, category: "fast", status: "out_of_stock", supplier: "Nordic Stitch AS", collection: "Coastal Charm", unitCost: 30, unitPrice: 122, reorderPoint: 45 },
  { sku: "CT-TP-004", productName: "Coastal Off-Shoulder Top", currentStock: 74, incomingStock: 0, salesLast30Days: 54, daysRemaining: 41, dailySalesVelocity: 1.8, category: "normal", status: "in_stock", supplier: "Linen House EU", collection: "Coastal Charm", unitCost: 20, unitPrice: 82, reorderPoint: 45 },
  { sku: "CT-AC-004", productName: "Coastal Anklet Set", currentStock: 136, incomingStock: 0, salesLast30Days: 46, daysRemaining: 89, dailySalesVelocity: 1.53, category: "normal", status: "in_stock", supplier: "Nordic Stitch AS", collection: "Coastal Charm", unitCost: 6, unitPrice: 24, reorderPoint: 40 },

  // ── Minimal Muse (MM) ──────────────────────────────────────────────
  { sku: "MM-DR-001", productName: "Minimal Slip Dress", currentStock: 106, incomingStock: 0, salesLast30Days: 72, daysRemaining: 44, dailySalesVelocity: 2.4, category: "fast", status: "in_stock", supplier: "Baltic Textiles OÜ", collection: "Minimal Muse", unitCost: 34, unitPrice: 138, reorderPoint: 55 },
  { sku: "MM-TP-001", productName: "Minimal Silk Cami", currentStock: 138, incomingStock: 0, salesLast30Days: 92, daysRemaining: 45, dailySalesVelocity: 3.07, category: "fast", status: "in_stock", supplier: "Baltic Textiles OÜ", collection: "Minimal Muse", unitCost: 20, unitPrice: 82, reorderPoint: 65 },
  { sku: "MM-PT-001", productName: "Minimal Wide-Leg Trouser", currentStock: 84, incomingStock: 80, salesLast30Days: 62, daysRemaining: 41, dailySalesVelocity: 2.07, category: "fast", status: "in_stock", supplier: "Tailor House OÜ", collection: "Minimal Muse", unitCost: 36, unitPrice: 145, reorderPoint: 55 },
  { sku: "MM-JK-001", productName: "Minimal Oversized Blazer", currentStock: 44, incomingStock: 0, salesLast30Days: 34, daysRemaining: 39, dailySalesVelocity: 1.13, category: "normal", status: "low_stock", supplier: "Baltic Textiles OÜ", collection: "Minimal Muse", unitCost: 56, unitPrice: 230, reorderPoint: 40 },
  { sku: "MM-SK-001", productName: "Minimal Column Skirt", currentStock: 62, incomingStock: 50, salesLast30Days: 44, daysRemaining: 42, dailySalesVelocity: 1.47, category: "normal", status: "in_stock", supplier: "Tailor House OÜ", collection: "Minimal Muse", unitCost: 26, unitPrice: 108, reorderPoint: 45 },
  { sku: "MM-DR-002", productName: "Minimal Knit Dress", currentStock: 58, incomingStock: 0, salesLast30Days: 42, daysRemaining: 41, dailySalesVelocity: 1.4, category: "normal", status: "in_stock", supplier: "Baltic Textiles OÜ", collection: "Minimal Muse", unitCost: 40, unitPrice: 162, reorderPoint: 45 },
  { sku: "MM-TP-002", productName: "Minimal Turtleneck", currentStock: 98, incomingStock: 0, salesLast30Days: 56, daysRemaining: 53, dailySalesVelocity: 1.87, category: "normal", status: "in_stock", supplier: "Tailor House OÜ", collection: "Minimal Muse", unitCost: 24, unitPrice: 98, reorderPoint: 50 },
  { sku: "MM-PT-002", productName: "Minimal Cropped Trouser", currentStock: 38, incomingStock: 0, salesLast30Days: 28, daysRemaining: 41, dailySalesVelocity: 0.93, category: "slow", status: "low_stock", supplier: "Baltic Textiles OÜ", collection: "Minimal Muse", unitCost: 30, unitPrice: 125, reorderPoint: 45 },
  { sku: "MM-DR-003", productName: "Minimal Midi Dress", currentStock: 72, incomingStock: 0, salesLast30Days: 48, daysRemaining: 45, dailySalesVelocity: 1.6, category: "normal", status: "in_stock", supplier: "Tailor House OÜ", collection: "Minimal Muse", unitCost: 38, unitPrice: 155, reorderPoint: 50 },
  { sku: "MM-AC-001", productName: "Minimal Leather Tote", currentStock: 84, incomingStock: 0, salesLast30Days: 52, daysRemaining: 48, dailySalesVelocity: 1.73, category: "normal", status: "in_stock", supplier: "Baltic Textiles OÜ", collection: "Minimal Muse", unitCost: 42, unitPrice: 170, reorderPoint: 45 },
  { sku: "MM-JR-001", productName: "Minimal Culotte Jumpsuit", currentStock: 36, incomingStock: 40, salesLast30Days: 24, daysRemaining: 45, dailySalesVelocity: 0.8, category: "slow", status: "low_stock", supplier: "Tailor House OÜ", collection: "Minimal Muse", unitCost: 46, unitPrice: 188, reorderPoint: 35 },
  { sku: "MM-TP-003", productName: "Minimal Boxy Tee", currentStock: 160, incomingStock: 0, salesLast30Days: 104, daysRemaining: 46, dailySalesVelocity: 3.47, category: "fast", status: "in_stock", supplier: "Baltic Textiles OÜ", collection: "Minimal Muse", unitCost: 14, unitPrice: 55, reorderPoint: 70 },
  { sku: "MM-PT-003", productName: "Minimal Flared Pant", currentStock: 48, incomingStock: 0, salesLast30Days: 32, daysRemaining: 45, dailySalesVelocity: 1.07, category: "normal", status: "low_stock", supplier: "Tailor House OÜ", collection: "Minimal Muse", unitCost: 32, unitPrice: 132, reorderPoint: 45 },
  { sku: "MM-SK-002", productName: "Minimal A-Line Midi Skirt", currentStock: 68, incomingStock: 0, salesLast30Days: 44, daysRemaining: 46, dailySalesVelocity: 1.47, category: "normal", status: "in_stock", supplier: "Baltic Textiles OÜ", collection: "Minimal Muse", unitCost: 28, unitPrice: 115, reorderPoint: 45 },
  { sku: "MM-DR-004", productName: "Minimal Shirt Dress", currentStock: 54, incomingStock: 50, salesLast30Days: 38, daysRemaining: 43, dailySalesVelocity: 1.27, category: "normal", status: "in_stock", supplier: "Tailor House OÜ", collection: "Minimal Muse", unitCost: 36, unitPrice: 145, reorderPoint: 45 },
  { sku: "MM-TP-004", productName: "Minimal Ribbed Tank", currentStock: 120, incomingStock: 0, salesLast30Days: 82, daysRemaining: 44, dailySalesVelocity: 2.73, category: "fast", status: "in_stock", supplier: "Baltic Textiles OÜ", collection: "Minimal Muse", unitCost: 12, unitPrice: 48, reorderPoint: 55 },
  { sku: "MM-AC-002", productName: "Minimal Hoop Earrings", currentStock: 148, incomingStock: 0, salesLast30Days: 86, daysRemaining: 52, dailySalesVelocity: 2.87, category: "fast", status: "in_stock", supplier: "Tailor House OÜ", collection: "Minimal Muse", unitCost: 6, unitPrice: 24, reorderPoint: 50 },
  { sku: "MM-DR-005", productName: "Minimal Tank Dress", currentStock: 2, incomingStock: 100, salesLast30Days: 52, daysRemaining: 1, dailySalesVelocity: 1.73, category: "fast", status: "critical", supplier: "Baltic Textiles OÜ", collection: "Minimal Muse", unitCost: 30, unitPrice: 122, reorderPoint: 50 },
  { sku: "MM-PT-004", productName: "Minimal Straight Leg Jean", currentStock: 92, incomingStock: 0, salesLast30Days: 58, daysRemaining: 48, dailySalesVelocity: 1.93, category: "normal", status: "in_stock", supplier: "Tailor House OÜ", collection: "Minimal Muse", unitCost: 34, unitPrice: 138, reorderPoint: 50 },
  { sku: "MM-AC-003", productName: "Minimal Watch", currentStock: 56, incomingStock: 0, salesLast30Days: 34, daysRemaining: 49, dailySalesVelocity: 1.13, category: "normal", status: "in_stock", supplier: "Baltic Textiles OÜ", collection: "Minimal Muse", unitCost: 28, unitPrice: 115, reorderPoint: 40 },

  // ── Bold Statement (BS) ────────────────────────────────────────────
  { sku: "BS-DR-001", productName: "Bold Statement Ruffle Gown", currentStock: 42, incomingStock: 40, salesLast30Days: 34, daysRemaining: 37, dailySalesVelocity: 1.13, category: "normal", status: "low_stock", supplier: "Atelier Tallinn", collection: "Bold Statement", unitCost: 62, unitPrice: 260, reorderPoint: 40 },
  { sku: "BS-JK-001", productName: "Statement Feather Blazer", currentStock: 28, incomingStock: 0, salesLast30Days: 18, daysRemaining: 47, dailySalesVelocity: 0.6, category: "slow", status: "low_stock", supplier: "Atelier Tallinn", collection: "Bold Statement", unitCost: 78, unitPrice: 320, reorderPoint: 30 },
  { sku: "BS-JK-002", productName: "Bold Colorblock Jacket", currentStock: 34, incomingStock: 0, salesLast30Days: 24, daysRemaining: 43, dailySalesVelocity: 0.8, category: "slow", status: "low_stock", supplier: "Atelier Tallinn", collection: "Bold Statement", unitCost: 58, unitPrice: 240, reorderPoint: 35 },
  { sku: "BS-TP-001", productName: "Statement Puff Sleeve Top", currentStock: 64, incomingStock: 60, salesLast30Days: 48, daysRemaining: 40, dailySalesVelocity: 1.6, category: "normal", status: "in_stock", supplier: "Atelier Tallinn", collection: "Bold Statement", unitCost: 32, unitPrice: 128, reorderPoint: 45 },
  { sku: "BS-DR-002", productName: "Bold Cutout Mini Dress", currentStock: 0, incomingStock: 80, salesLast30Days: 42, daysRemaining: 0, dailySalesVelocity: 1.4, category: "fast", status: "out_of_stock", supplier: "Atelier Tallinn", collection: "Bold Statement", unitCost: 44, unitPrice: 185, reorderPoint: 45 },
  { sku: "BS-PT-001", productName: "Statement Wide-Leg Trouser", currentStock: 38, incomingStock: 50, salesLast30Days: 28, daysRemaining: 41, dailySalesVelocity: 0.93, category: "slow", status: "low_stock", supplier: "Atelier Tallinn", collection: "Bold Statement", unitCost: 42, unitPrice: 175, reorderPoint: 40 },
  { sku: "BS-SK-001", productName: "Bold Metallic Midi Skirt", currentStock: 52, incomingStock: 0, salesLast30Days: 36, daysRemaining: 43, dailySalesVelocity: 1.2, category: "normal", status: "in_stock", supplier: "Atelier Tallinn", collection: "Bold Statement", unitCost: 38, unitPrice: 155, reorderPoint: 40 },
  { sku: "BS-TP-002", productName: "Bold Animal Print Blouse", currentStock: 46, incomingStock: 0, salesLast30Days: 32, daysRemaining: 43, dailySalesVelocity: 1.07, category: "normal", status: "low_stock", supplier: "Atelier Tallinn", collection: "Bold Statement", unitCost: 30, unitPrice: 122, reorderPoint: 40 },
  { sku: "BS-JR-001", productName: "Statement Sequined Jumpsuit", currentStock: 22, incomingStock: 0, salesLast30Days: 16, daysRemaining: 41, dailySalesVelocity: 0.53, category: "slow", status: "low_stock", supplier: "Atelier Tallinn", collection: "Bold Statement", unitCost: 56, unitPrice: 235, reorderPoint: 30 },
  { sku: "BS-AC-001", productName: "Statement Chandelier Earrings", currentStock: 68, incomingStock: 0, salesLast30Days: 44, daysRemaining: 46, dailySalesVelocity: 1.47, category: "normal", status: "in_stock", supplier: "Atelier Tallinn", collection: "Bold Statement", unitCost: 14, unitPrice: 58, reorderPoint: 40 },
  { sku: "BS-DR-003", productName: "Bold One Sleeve Dress", currentStock: 36, incomingStock: 0, salesLast30Days: 26, daysRemaining: 42, dailySalesVelocity: 0.87, category: "slow", status: "low_stock", supplier: "Atelier Tallinn", collection: "Bold Statement", unitCost: 48, unitPrice: 198, reorderPoint: 35 },
  { sku: "BS-AC-002", productName: "Statement Cuff Bracelet", currentStock: 52, incomingStock: 50, salesLast30Days: 34, daysRemaining: 46, dailySalesVelocity: 1.13, category: "normal", status: "in_stock", supplier: "Atelier Tallinn", collection: "Bold Statement", unitCost: 10, unitPrice: 42, reorderPoint: 35 },
  { sku: "BS-TP-003", productName: "Statement Corset Top", currentStock: 44, incomingStock: 0, salesLast30Days: 34, daysRemaining: 39, dailySalesVelocity: 1.13, category: "normal", status: "low_stock", supplier: "Atelier Tallinn", collection: "Bold Statement", unitCost: 34, unitPrice: 138, reorderPoint: 40 },
  { sku: "BS-JK-003", productName: "Statement Embellished Jacket", currentStock: 16, incomingStock: 0, salesLast30Days: 12, daysRemaining: 40, dailySalesVelocity: 0.4, category: "slow", status: "low_stock", supplier: "Atelier Tallinn", collection: "Bold Statement", unitCost: 72, unitPrice: 298, reorderPoint: 25 },
  { sku: "BS-DR-004", productName: "Bold Neon Midi Dress", currentStock: 48, incomingStock: 50, salesLast30Days: 38, daysRemaining: 38, dailySalesVelocity: 1.27, category: "normal", status: "low_stock", supplier: "Atelier Tallinn", collection: "Bold Statement", unitCost: 40, unitPrice: 168, reorderPoint: 45 },
  { sku: "BS-PT-002", productName: "Statement Leather Pant", currentStock: 28, incomingStock: 0, salesLast30Days: 22, daysRemaining: 38, dailySalesVelocity: 0.73, category: "slow", status: "low_stock", supplier: "Atelier Tallinn", collection: "Bold Statement", unitCost: 52, unitPrice: 215, reorderPoint: 35 },
  { sku: "BS-SK-002", productName: "Bold Printed Maxi Skirt", currentStock: 42, incomingStock: 0, salesLast30Days: 28, daysRemaining: 45, dailySalesVelocity: 0.93, category: "slow", status: "low_stock", supplier: "Atelier Tallinn", collection: "Bold Statement", unitCost: 36, unitPrice: 148, reorderPoint: 40 },
  { sku: "BS-AC-003", productName: "Statement Oversized Sunnies", currentStock: 88, incomingStock: 0, salesLast30Days: 52, daysRemaining: 51, dailySalesVelocity: 1.73, category: "normal", status: "in_stock", supplier: "Atelier Tallinn", collection: "Bold Statement", unitCost: 12, unitPrice: 48, reorderPoint: 45 },
  { sku: "BS-TP-004", productName: "Bold Graphic Print Tee", currentStock: 76, incomingStock: 0, salesLast30Days: 44, daysRemaining: 52, dailySalesVelocity: 1.47, category: "normal", status: "in_stock", supplier: "Atelier Tallinn", collection: "Bold Statement", unitCost: 16, unitPrice: 65, reorderPoint: 45 },
  { sku: "BS-JR-002", productName: "Bold Overalls", currentStock: 32, incomingStock: 40, salesLast30Days: 18, daysRemaining: 53, dailySalesVelocity: 0.6, category: "slow", status: "low_stock", supplier: "Atelier Tallinn", collection: "Bold Statement", unitCost: 48, unitPrice: 198, reorderPoint: 35 },

  // ── Eco Essence (EE) ───────────────────────────────────────────────
  { sku: "EE-DR-001", productName: "Eco Hemp Midi Dress", currentStock: 82, incomingStock: 60, salesLast30Days: 58, daysRemaining: 42, dailySalesVelocity: 1.93, category: "normal", status: "in_stock", supplier: "Eco Fiber Co", collection: "Eco Essence", unitCost: 30, unitPrice: 125, reorderPoint: 50 },
  { sku: "EE-TP-001", productName: "Eco Organic Cotton Tee", currentStock: 168, incomingStock: 0, salesLast30Days: 114, daysRemaining: 44, dailySalesVelocity: 3.8, category: "fast", status: "in_stock", supplier: "Eco Fiber Co", collection: "Eco Essence", unitCost: 10, unitPrice: 42, reorderPoint: 75 },
  { sku: "EE-TP-002", productName: "Eco Bamboo Blouse", currentStock: 72, incomingStock: 80, salesLast30Days: 54, daysRemaining: 40, dailySalesVelocity: 1.8, category: "normal", status: "in_stock", supplier: "Eco Fiber Co", collection: "Eco Essence", unitCost: 22, unitPrice: 88, reorderPoint: 50 },
  { sku: "EE-PT-001", productName: "Eco Recycled Denim Jean", currentStock: 94, incomingStock: 0, salesLast30Days: 68, daysRemaining: 41, dailySalesVelocity: 2.27, category: "fast", status: "in_stock", supplier: "Eco Fiber Co", collection: "Eco Essence", unitCost: 28, unitPrice: 115, reorderPoint: 55 },
  { sku: "EE-DR-002", productName: "Eco Tencel Shirt Dress", currentStock: 56, incomingStock: 0, salesLast30Days: 42, daysRemaining: 40, dailySalesVelocity: 1.4, category: "normal", status: "in_stock", supplier: "Eco Fiber Co", collection: "Eco Essence", unitCost: 34, unitPrice: 140, reorderPoint: 45 },
  { sku: "EE-JK-001", productName: "Eco Linen Blazer", currentStock: 38, incomingStock: 0, salesLast30Days: 26, daysRemaining: 44, dailySalesVelocity: 0.87, category: "slow", status: "low_stock", supplier: "Eco Fiber Co", collection: "Eco Essence", unitCost: 54, unitPrice: 220, reorderPoint: 35 },
  { sku: "EE-SK-001", productName: "Eco Hemp Wrap Skirt", currentStock: 62, incomingStock: 50, salesLast30Days: 46, daysRemaining: 40, dailySalesVelocity: 1.53, category: "normal", status: "in_stock", supplier: "Eco Fiber Co", collection: "Eco Essence", unitCost: 22, unitPrice: 92, reorderPoint: 45 },
  { sku: "EE-PT-002", productName: "Eco Wide-Leg Linen Pant", currentStock: 84, incomingStock: 0, salesLast30Days: 60, daysRemaining: 42, dailySalesVelocity: 2.0, category: "fast", status: "in_stock", supplier: "Eco Fiber Co", collection: "Eco Essence", unitCost: 30, unitPrice: 122, reorderPoint: 50 },
  { sku: "EE-SH-001", productName: "Eco Organic Shorts", currentStock: 54, incomingStock: 100, salesLast30Days: 44, daysRemaining: 37, dailySalesVelocity: 1.47, category: "normal", status: "in_stock", supplier: "Eco Fiber Co", collection: "Eco Essence", unitCost: 16, unitPrice: 65, reorderPoint: 45 },
  { sku: "EE-DR-003", productName: "Eco Modal Wrap Dress", currentStock: 64, incomingStock: 0, salesLast30Days: 48, daysRemaining: 40, dailySalesVelocity: 1.6, category: "normal", status: "in_stock", supplier: "Eco Fiber Co", collection: "Eco Essence", unitCost: 32, unitPrice: 132, reorderPoint: 45 },
  { sku: "EE-AC-001", productName: "Eco Cork Crossbody Bag", currentStock: 74, incomingStock: 0, salesLast30Days: 50, daysRemaining: 44, dailySalesVelocity: 1.67, category: "normal", status: "in_stock", supplier: "Eco Fiber Co", collection: "Eco Essence", unitCost: 20, unitPrice: 82, reorderPoint: 45 },
  { sku: "EE-TP-003", productName: "Eco Linen Tank", currentStock: 134, incomingStock: 0, salesLast30Days: 96, daysRemaining: 42, dailySalesVelocity: 3.2, category: "fast", status: "in_stock", supplier: "Eco Fiber Co", collection: "Eco Essence", unitCost: 14, unitPrice: 55, reorderPoint: 60 },
  { sku: "EE-JR-001", productName: "Eco Cotton Jumpsuit", currentStock: 46, incomingStock: 40, salesLast30Days: 36, daysRemaining: 38, dailySalesVelocity: 1.2, category: "normal", status: "low_stock", supplier: "Eco Fiber Co", collection: "Eco Essence", unitCost: 40, unitPrice: 165, reorderPoint: 45 },
  { sku: "EE-SK-002", productName: "Eco Recycled Pleated Skirt", currentStock: 48, incomingStock: 0, salesLast30Days: 34, daysRemaining: 42, dailySalesVelocity: 1.13, category: "normal", status: "low_stock", supplier: "Eco Fiber Co", collection: "Eco Essence", unitCost: 24, unitPrice: 98, reorderPoint: 40 },
  { sku: "EE-DR-004", productName: "Eco Ribbed Tank Dress", currentStock: 0, incomingStock: 120, salesLast30Days: 52, daysRemaining: 0, dailySalesVelocity: 1.73, category: "fast", status: "out_of_stock", supplier: "Eco Fiber Co", collection: "Eco Essence", unitCost: 26, unitPrice: 108, reorderPoint: 50 },
  { sku: "EE-PT-003", productName: "Eco Culotte Pant", currentStock: 36, incomingStock: 0, salesLast30Days: 22, daysRemaining: 49, dailySalesVelocity: 0.73, category: "slow", status: "low_stock", supplier: "Eco Fiber Co", collection: "Eco Essence", unitCost: 28, unitPrice: 118, reorderPoint: 40 },
  { sku: "EE-AC-002", productName: "Eco Beaded Bracelet Set", currentStock: 112, incomingStock: 0, salesLast30Days: 62, daysRemaining: 54, dailySalesVelocity: 2.07, category: "fast", status: "in_stock", supplier: "Eco Fiber Co", collection: "Eco Essence", unitCost: 6, unitPrice: 24, reorderPoint: 50 },
  { sku: "EE-TP-004", productName: "Eco Cropped Sweatshirt", currentStock: 68, incomingStock: 0, salesLast30Days: 42, daysRemaining: 49, dailySalesVelocity: 1.4, category: "normal", status: "in_stock", supplier: "Eco Fiber Co", collection: "Eco Essence", unitCost: 18, unitPrice: 72, reorderPoint: 45 },
  { sku: "EE-DR-005", productName: "Eco Tiered Maxi Dress", currentStock: 52, incomingStock: 60, salesLast30Days: 40, daysRemaining: 39, dailySalesVelocity: 1.33, category: "normal", status: "in_stock", supplier: "Eco Fiber Co", collection: "Eco Essence", unitCost: 36, unitPrice: 148, reorderPoint: 45 },
  { sku: "EE-AC-003", productName: "Eco Canvas Sneakers", currentStock: 88, incomingStock: 0, salesLast30Days: 56, daysRemaining: 47, dailySalesVelocity: 1.87, category: "normal", status: "in_stock", supplier: "Eco Fiber Co", collection: "Eco Essence", unitCost: 24, unitPrice: 98, reorderPoint: 50 },
];

// ---------------------------------------------------------------------------
// Forecast Items — 50 items (~5 per collection)
// ---------------------------------------------------------------------------

const forecasts: ForecastItem[] = [
  // Summer Breeze
  { sku: "SB-DR-001", productName: "Summer Breeze Midi Dress", collection: "Summer Breeze", currentStock: 210, incomingStock: 100, unitsNeeded: 0, expectedDemand: 145, recommendedProduction: 50, safetyStock: 75, collectionRecommendation: "Maintain — demand stable", priorityLevel: "low", forecastPeriod: 30, forecastDate: "2026-07-15", salesVelocity: 4.83 },
  { sku: "SB-DR-003", productName: "Sunlit Tiered Dress", collection: "Summer Breeze", currentStock: 3, incomingStock: 200, unitsNeeded: 0, expectedDemand: 160, recommendedProduction: 0, safetyStock: 50, collectionRecommendation: "Incoming shipment covers demand", priorityLevel: "medium", forecastPeriod: 30, forecastDate: "2026-07-15", salesVelocity: 1.6 },
  { sku: "SB-SK-002", productName: "Sunlit Wrap Skirt", collection: "Summer Breeze", currentStock: 5, incomingStock: 0, unitsNeeded: 75, expectedDemand: 38, recommendedProduction: 95, safetyStock: 45, collectionRecommendation: "URGENT — stock out imminent without production", priorityLevel: "critical", forecastPeriod: 30, forecastDate: "2026-07-05", salesVelocity: 1.27 },
  { sku: "SB-DR-005", productName: "Sunlit Wrap Maxi Dress", collection: "Summer Breeze", currentStock: 0, incomingStock: 0, unitsNeeded: 100, expectedDemand: 52, recommendedProduction: 120, safetyStock: 55, collectionRecommendation: "Immediate restock needed — lost sales high", priorityLevel: "critical", forecastPeriod: 30, forecastDate: "2026-07-05", salesVelocity: 1.73 },
  { sku: "SB-AC-002", productName: "Sunlit Straw Hat", collection: "Summer Breeze", currentStock: 0, incomingStock: 120, unitsNeeded: 0, expectedDemand: 44, recommendedProduction: 0, safetyStock: 50, collectionRecommendation: "Incoming shipment adequate", priorityLevel: "low", forecastPeriod: 30, forecastDate: "2026-07-15", salesVelocity: 1.47 },

  // Linen Luxe
  { sku: "LN-DR-001", productName: "Linen Wrap Dress", collection: "Linen Luxe", currentStock: 173, incomingStock: 80, unitsNeeded: 0, expectedDemand: 130, recommendedProduction: 0, safetyStock: 80, collectionRecommendation: "Healthy stock — no action needed", priorityLevel: "low", forecastPeriod: 30, forecastDate: "2026-07-15", salesVelocity: 4.33 },
  { sku: "LN-DR-002", productName: "Linen Maxi Dress", collection: "Linen Luxe", currentStock: 3, incomingStock: 150, unitsNeeded: 0, expectedDemand: 72, recommendedProduction: 40, safetyStock: 70, collectionRecommendation: "Monitor closely; incoming covers short-term", priorityLevel: "high", forecastPeriod: 30, forecastDate: "2026-07-10", salesVelocity: 2.4 },
  { sku: "LN-DR-005", productName: "Linen Tiered Sundress", collection: "Linen Luxe", currentStock: 0, incomingStock: 120, unitsNeeded: 0, expectedDemand: 56, recommendedProduction: 40, safetyStock: 55, collectionRecommendation: "Incoming shipment covers 60d demand", priorityLevel: "medium", forecastPeriod: 30, forecastDate: "2026-07-15", salesVelocity: 1.87 },
  { sku: "LN-PT-003", productName: "Luxe Cropped Linen Pant", collection: "Linen Luxe", currentStock: 22, incomingStock: 50, unitsNeeded: 0, expectedDemand: 14, recommendedProduction: 0, safetyStock: 45, collectionRecommendation: "Low velocity — consider discounting before restock", priorityLevel: "medium", forecastPeriod: 60, forecastDate: "2026-07-20", salesVelocity: 0.47 },
  { sku: "LN-JK-001", productName: "Linen Relaxed Blazer", collection: "Linen Luxe", currentStock: 38, incomingStock: 40, unitsNeeded: 0, expectedDemand: 24, recommendedProduction: 0, safetyStock: 40, collectionRecommendation: "Sufficient for next 60d", priorityLevel: "low", forecastPeriod: 60, forecastDate: "2026-07-20", salesVelocity: 0.8 },

  // Evening Bloom
  { sku: "EB-DR-004", productName: "Bloom Strapless Gown", collection: "Evening Bloom", currentStock: 2, incomingStock: 80, unitsNeeded: 20, expectedDemand: 36, recommendedProduction: 60, safetyStock: 40, collectionRecommendation: "Restock to maintain wedding season demand", priorityLevel: "high", forecastPeriod: 30, forecastDate: "2026-07-10", salesVelocity: 1.2 },
  { sku: "EB-DR-005", productName: "Noir One-Shoulder Dress", collection: "Evening Bloom", currentStock: 0, incomingStock: 100, unitsNeeded: 0, expectedDemand: 42, recommendedProduction: 30, safetyStock: 45, collectionRecommendation: "Incoming stock covers 60d demand", priorityLevel: "medium", forecastPeriod: 30, forecastDate: "2026-07-15", salesVelocity: 1.4 },
  { sku: "EB-JK-001", productName: "Noir Tailored Blazer", collection: "Evening Bloom", currentStock: 38, incomingStock: 0, unitsNeeded: 0, expectedDemand: 22, recommendedProduction: 0, safetyStock: 35, collectionRecommendation: "Slow but steady — plan seasonal production", priorityLevel: "low", forecastPeriod: 60, forecastDate: "2026-08-01", salesVelocity: 0.73 },
  { sku: "EB-JR-002", productName: "Bloom Romper", collection: "Evening Bloom", currentStock: 56, incomingStock: 40, unitsNeeded: 0, expectedDemand: 38, recommendedProduction: 0, safetyStock: 45, collectionRecommendation: "Well-stocked through summer", priorityLevel: "low", forecastPeriod: 30, forecastDate: "2026-07-15", salesVelocity: 1.27 },
  { sku: "EB-TP-004", productName: "Blossom Embroidered Top", collection: "Evening Bloom", currentStock: 46, incomingStock: 0, unitsNeeded: 0, expectedDemand: 26, recommendedProduction: 0, safetyStock: 40, collectionRecommendation: "Reduce price to clear before fall", priorityLevel: "medium", forecastPeriod: 60, forecastDate: "2026-07-20", salesVelocity: 0.87 },

  // Urban Edge
  { sku: "UE-PT-001", productName: "Edge Cargo Pant", collection: "Urban Edge", currentStock: 96, incomingStock: 80, unitsNeeded: 0, expectedDemand: 72, recommendedProduction: 40, safetyStock: 55, collectionRecommendation: "Strong seller — maintain pipeline", priorityLevel: "low", forecastPeriod: 30, forecastDate: "2026-07-15", salesVelocity: 2.4 },
  { sku: "UE-SH-002", productName: "Edge Bike Shorts", collection: "Urban Edge", currentStock: 0, incomingStock: 100, unitsNeeded: 0, expectedDemand: 44, recommendedProduction: 50, safetyStock: 45, collectionRecommendation: "Prepare for reorder after incoming clears", priorityLevel: "high", forecastPeriod: 30, forecastDate: "2026-07-10", salesVelocity: 1.47 },
  { sku: "UE-JK-003", productName: "Urban Bomber Jacket", collection: "Urban Edge", currentStock: 28, incomingStock: 0, unitsNeeded: 0, expectedDemand: 20, recommendedProduction: 0, safetyStock: 35, collectionRecommendation: "Hold production until Q3 forecast firms", priorityLevel: "medium", forecastPeriod: 60, forecastDate: "2026-08-01", salesVelocity: 0.67 },
  { sku: "UE-AC-003", productName: "Urban Beanie", collection: "Urban Edge", currentStock: 144, incomingStock: 0, unitsNeeded: 0, expectedDemand: 34, recommendedProduction: 0, safetyStock: 40, collectionRecommendation: "Overstocked — transfer to outlet", priorityLevel: "low", forecastPeriod: 60, forecastDate: "2026-08-01", salesVelocity: 1.13 },
  { sku: "UE-JR-001", productName: "Urban Utility Jumpsuit", collection: "Urban Edge", currentStock: 34, incomingStock: 0, unitsNeeded: 20, expectedDemand: 24, recommendedProduction: 30, safetyStock: 40, collectionRecommendation: "Niche item — small batch recommended", priorityLevel: "medium", forecastPeriod: 60, forecastDate: "2026-07-20", salesVelocity: 0.8 },

  // Boho Spirit
  { sku: "BH-TP-003", productName: "Boho Peasant Top", collection: "Boho Spirit", currentStock: 148, incomingStock: 0, unitsNeeded: 0, expectedDemand: 110, recommendedProduction: 50, safetyStock: 70, collectionRecommendation: "Strong demand — restock at 60 units", priorityLevel: "low", forecastPeriod: 30, forecastDate: "2026-07-15", salesVelocity: 3.67 },
  { sku: "BH-DR-002", productName: "Boho Tiered Sundress", collection: "Boho Spirit", currentStock: 2, incomingStock: 100, unitsNeeded: 0, expectedDemand: 56, recommendedProduction: 30, safetyStock: 55, collectionRecommendation: "Incoming + small buffer production", priorityLevel: "high", forecastPeriod: 30, forecastDate: "2026-07-10", salesVelocity: 1.87 },
  { sku: "BH-DR-004", productName: "Spirit Off-Shoulder Dress", collection: "Boho Spirit", currentStock: 0, incomingStock: 120, unitsNeeded: 0, expectedDemand: 48, recommendedProduction: 30, safetyStock: 50, collectionRecommendation: "Good incoming coverage", priorityLevel: "medium", forecastPeriod: 30, forecastDate: "2026-07-15", salesVelocity: 1.6 },
  { sku: "BH-TP-005", productName: "Boho Patterned Kimono Top", collection: "Boho Spirit", currentStock: 42, incomingStock: 0, unitsNeeded: 0, expectedDemand: 28, recommendedProduction: 0, safetyStock: 40, collectionRecommendation: "Sufficient — reassess in 45d", priorityLevel: "low", forecastPeriod: 60, forecastDate: "2026-07-20", salesVelocity: 0.93 },
  { sku: "BH-SK-002", productName: "Spirit Embroidered Midi", collection: "Boho Spirit", currentStock: 32, incomingStock: 50, unitsNeeded: 0, expectedDemand: 26, recommendedProduction: 0, safetyStock: 40, collectionRecommendation: "Incoming covers slow demand", priorityLevel: "low", forecastPeriod: 60, forecastDate: "2026-08-01", salesVelocity: 0.87 },

  // Classic Core
  { sku: "CC-TP-001", productName: "Classic Silk Blouse", collection: "Classic Core", currentStock: 142, incomingStock: 80, unitsNeeded: 0, expectedDemand: 108, recommendedProduction: 40, safetyStock: 70, collectionRecommendation: "Evergreen — maintain steady orders", priorityLevel: "low", forecastPeriod: 30, forecastDate: "2026-07-15", salesVelocity: 3.6 },
  { sku: "CC-PT-003", productName: "Classic Wide-Leg Slacks", collection: "Classic Core", currentStock: 36, incomingStock: 0, unitsNeeded: 30, expectedDemand: 24, recommendedProduction: 45, safetyStock: 45, collectionRecommendation: "Slow but key staple — small qty reorder", priorityLevel: "medium", forecastPeriod: 60, forecastDate: "2026-07-20", salesVelocity: 0.8 },
  { sku: "CC-JK-002", productName: "Classic Trench Coat", collection: "Classic Core", currentStock: 42, incomingStock: 0, unitsNeeded: 0, expectedDemand: 28, recommendedProduction: 0, safetyStock: 40, collectionRecommendation: "Off-season — plan fall production", priorityLevel: "low", forecastPeriod: 90, forecastDate: "2026-08-15", salesVelocity: 0.93 },
  { sku: "CC-JR-001", productName: "Classic Crepe Jumpsuit", collection: "Classic Core", currentStock: 34, incomingStock: 40, unitsNeeded: 0, expectedDemand: 26, recommendedProduction: 0, safetyStock: 40, collectionRecommendation: "Incoming shipment adequate", priorityLevel: "low", forecastPeriod: 60, forecastDate: "2026-07-20", salesVelocity: 0.87 },
  { sku: "CC-AC-003", productName: "Classic Pearl Studs", collection: "Classic Core", currentStock: 156, incomingStock: 0, unitsNeeded: 0, expectedDemand: 78, recommendedProduction: 50, safetyStock: 50, collectionRecommendation: "High margin staple — maintain stock", priorityLevel: "low", forecastPeriod: 30, forecastDate: "2026-07-15", salesVelocity: 2.6 },

  // Coastal Charm
  { sku: "CT-DR-001", productName: "Coastal Linen Sundress", collection: "Coastal Charm", currentStock: 88, incomingStock: 100, unitsNeeded: 0, expectedDemand: 72, recommendedProduction: 30, safetyStock: 60, collectionRecommendation: "Healthy — prepare for peak summer", priorityLevel: "low", forecastPeriod: 30, forecastDate: "2026-07-15", salesVelocity: 2.4 },
  { sku: "CT-DR-002", productName: "Coastal Maxi Dress", collection: "Coastal Charm", currentStock: 4, incomingStock: 80, unitsNeeded: 30, expectedDemand: 58, recommendedProduction: 50, safetyStock: 55, collectionRecommendation: "Below safety stock — expedite", priorityLevel: "critical", forecastPeriod: 30, forecastDate: "2026-07-05", salesVelocity: 1.93 },
  { sku: "CT-DR-004", productName: "Coastal Tie-Dye Dress", collection: "Coastal Charm", currentStock: 0, incomingStock: 120, unitsNeeded: 0, expectedDemand: 44, recommendedProduction: 0, safetyStock: 45, collectionRecommendation: "Incoming covers 90d demand", priorityLevel: "low", forecastPeriod: 30, forecastDate: "2026-07-15", salesVelocity: 1.47 },
  { sku: "CT-PT-003", productName: "Coastal Capri Pant", collection: "Coastal Charm", currentStock: 22, incomingStock: 50, unitsNeeded: 0, expectedDemand: 16, recommendedProduction: 0, safetyStock: 45, collectionRecommendation: "Low interest — markdown and discontinue", priorityLevel: "medium", forecastPeriod: 60, forecastDate: "2026-07-20", salesVelocity: 0.53 },
  { sku: "CT-PT-002", productName: "Coastal Linen Trouser", collection: "Coastal Charm", currentStock: 168, incomingStock: 100, unitsNeeded: 0, expectedDemand: 124, recommendedProduction: 50, safetyStock: 70, collectionRecommendation: "Top seller — keep production ahead of demand", priorityLevel: "low", forecastPeriod: 30, forecastDate: "2026-07-15", salesVelocity: 4.13 },

  // Minimal Muse
  { sku: "MM-DR-005", productName: "Minimal Tank Dress", collection: "Minimal Muse", currentStock: 2, incomingStock: 100, unitsNeeded: 20, expectedDemand: 52, recommendedProduction: 40, safetyStock: 50, collectionRecommendation: "Nearing stockout — cover with incoming + new order", priorityLevel: "high", forecastPeriod: 30, forecastDate: "2026-07-10", salesVelocity: 1.73 },
  { sku: "MM-PT-002", productName: "Minimal Cropped Trouser", collection: "Minimal Muse", currentStock: 38, incomingStock: 0, unitsNeeded: 25, expectedDemand: 28, recommendedProduction: 40, safetyStock: 45, collectionRecommendation: "Slow seller — small-batch restock only", priorityLevel: "medium", forecastPeriod: 60, forecastDate: "2026-07-20", salesVelocity: 0.93 },
  { sku: "MM-JR-001", productName: "Minimal Culotte Jumpsuit", collection: "Minimal Muse", currentStock: 36, incomingStock: 40, unitsNeeded: 0, expectedDemand: 24, recommendedProduction: 0, safetyStock: 35, collectionRecommendation: "Adequate — monitor for fall", priorityLevel: "low", forecastPeriod: 60, forecastDate: "2026-07-20", salesVelocity: 0.8 },
  { sku: "MM-TP-003", productName: "Minimal Boxy Tee", collection: "Minimal Muse", currentStock: 160, incomingStock: 0, unitsNeeded: 0, expectedDemand: 104, recommendedProduction: 60, safetyStock: 70, collectionRecommendation: "Volume staple — place bulk order", priorityLevel: "low", forecastPeriod: 30, forecastDate: "2026-07-15", salesVelocity: 3.47 },
  { sku: "MM-AC-002", productName: "Minimal Hoop Earrings", collection: "Minimal Muse", currentStock: 148, incomingStock: 0, unitsNeeded: 0, expectedDemand: 86, recommendedProduction: 0, safetyStock: 50, collectionRecommendation: "Well-stocked — reassess in 60d", priorityLevel: "low", forecastPeriod: 30, forecastDate: "2026-07-15", salesVelocity: 2.87 },

  // Bold Statement
  { sku: "BS-DR-002", productName: "Bold Cutout Mini Dress", collection: "Bold Statement", currentStock: 0, incomingStock: 80, unitsNeeded: 0, expectedDemand: 42, recommendedProduction: 30, safetyStock: 45, collectionRecommendation: "Incoming covers demand; add buffer", priorityLevel: "medium", forecastPeriod: 30, forecastDate: "2026-07-15", salesVelocity: 1.4 },
  { sku: "BS-JK-001", productName: "Statement Feather Blazer", collection: "Bold Statement", currentStock: 28, incomingStock: 0, unitsNeeded: 0, expectedDemand: 18, recommendedProduction: 0, safetyStock: 30, collectionRecommendation: "Premium niche — made-to-order candidate", priorityLevel: "low", forecastPeriod: 60, forecastDate: "2026-08-01", salesVelocity: 0.6 },
  { sku: "BS-JK-003", productName: "Statement Embellished Jacket", collection: "Bold Statement", currentStock: 16, incomingStock: 0, unitsNeeded: 0, expectedDemand: 12, recommendedProduction: 0, safetyStock: 25, collectionRecommendation: "High price low volume — no restock", priorityLevel: "low", forecastPeriod: 60, forecastDate: "2026-08-01", salesVelocity: 0.4 },
  { sku: "BS-DR-003", productName: "Bold One Sleeve Dress", collection: "Bold Statement", currentStock: 36, incomingStock: 0, unitsNeeded: 0, expectedDemand: 26, recommendedProduction: 0, safetyStock: 35, collectionRecommendation: "Sufficient — trending down", priorityLevel: "low", forecastPeriod: 60, forecastDate: "2026-07-20", salesVelocity: 0.87 },
  { sku: "BS-JR-002", productName: "Bold Overalls", collection: "Bold Statement", currentStock: 32, incomingStock: 40, unitsNeeded: 0, expectedDemand: 18, recommendedProduction: 0, safetyStock: 35, collectionRecommendation: "Incoming covers fall season", priorityLevel: "low", forecastPeriod: 60, forecastDate: "2026-08-15", salesVelocity: 0.6 },

  // Eco Essence
  { sku: "EE-DR-004", productName: "Eco Ribbed Tank Dress", collection: "Eco Essence", currentStock: 0, incomingStock: 120, unitsNeeded: 0, expectedDemand: 52, recommendedProduction: 30, safetyStock: 50, collectionRecommendation: "Good incoming — add buffer for season", priorityLevel: "medium", forecastPeriod: 30, forecastDate: "2026-07-15", salesVelocity: 1.73 },
  { sku: "EE-JK-001", productName: "Eco Linen Blazer", collection: "Eco Essence", currentStock: 38, incomingStock: 0, unitsNeeded: 0, expectedDemand: 26, recommendedProduction: 0, safetyStock: 35, collectionRecommendation: "Slow — plan for fall relaunch", priorityLevel: "low", forecastPeriod: 60, forecastDate: "2026-08-01", salesVelocity: 0.87 },
  { sku: "EE-PT-003", productName: "Eco Culotte Pant", collection: "Eco Essence", currentStock: 36, incomingStock: 0, unitsNeeded: 0, expectedDemand: 22, recommendedProduction: 0, safetyStock: 40, collectionRecommendation: "Low velocity — consider style refresh", priorityLevel: "low", forecastPeriod: 60, forecastDate: "2026-07-20", salesVelocity: 0.73 },
  { sku: "EE-TP-001", productName: "Eco Organic Cotton Tee", collection: "Eco Essence", currentStock: 168, incomingStock: 0, unitsNeeded: 0, expectedDemand: 114, recommendedProduction: 70, safetyStock: 75, collectionRecommendation: "Volume staple — ensure continuous supply", priorityLevel: "low", forecastPeriod: 30, forecastDate: "2026-07-15", salesVelocity: 3.8 },
  { sku: "EE-TP-003", productName: "Eco Linen Tank", collection: "Eco Essence", currentStock: 134, incomingStock: 0, unitsNeeded: 0, expectedDemand: 96, recommendedProduction: 50, safetyStock: 60, collectionRecommendation: "Strong summer performer", priorityLevel: "low", forecastPeriod: 30, forecastDate: "2026-07-15", salesVelocity: 3.2 },
];

// ---------------------------------------------------------------------------
// Service Functions
// ---------------------------------------------------------------------------

export async function getInventory(): Promise<InventoryItem[]> {
  await delay(randomBetween(400, 700));
  return inventory;
}

export async function getForecasts(): Promise<ForecastItem[]> {
  await delay(randomBetween(350, 650));
  return forecasts;
}

export async function getProductClassification(): Promise<ProductClassification> {
  await delay(randomBetween(300, 550));

  return {
    fastMoving: inventory.filter((i) => i.category === "fast"),
    slowMoving: inventory.filter((i) => i.category === "slow"),
    normal: inventory.filter((i) => i.category === "normal"),
  };
}
