"use client";

import { useState, useEffect } from "react";
import { getMonthlyReport } from "@/services/dashboardService";
import type { MonthlyReport } from "@/types/index";
import { formatCurrency, formatPercent, cn } from "@/lib/utils";
import { format } from "date-fns";
import {
  FileText,
  Download,
  Sparkles,
  TrendingUp,
  DollarSign,
  Megaphone,
  Package,
  Star,
  ArrowUpRight,
  Calendar,
} from "lucide-react";

// ============================================================
// Constants
// ============================================================

const CARD =
  "bg-[var(--neutral-primary-soft)] border border-[var(--border-default)] rounded-[2px] shadow-[var(--shadow-xs)]";

const GRADIENT_BRAND: React.CSSProperties = {
  background: "linear-gradient(135deg, #C8399C 0%, #7C3AED 100%)",
};

const CHANNEL_COLORS = [
  "var(--brand)",
  "var(--purple)",
  "var(--sky)",
  "var(--teal)",
  "var(--orange)",
  "var(--body-subtle)",
];

// ============================================================
// Component
// ============================================================

export default function ReportsPage() {
  const [report, setReport] = useState<MonthlyReport | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    async function load() {
      setLoading(true);
      setError(null);
      try {
        const data = await getMonthlyReport();
        setReport(data);
      } catch (err) {
        setError(
          err instanceof Error ? err.message : "Failed to load report"
        );
      } finally {
        setLoading(false);
      }
    }
    load();
  }, []);

  const handleExport = (type: string) => {
    alert("Export started...");
  };

  // ============================================================
  // Error State
  // ============================================================

  if (error) {
    return (
      <div className="max-w-[1200px] mx-auto px-6">
        <div className={cn(CARD, "text-center py-16")}>
          <p className="text-[14px] font-semibold text-[var(--danger)] mb-4">
            {error}
          </p>
          <button
            onClick={() => window.location.reload()}
            className="px-4 py-2.5 text-[14px] font-semibold text-white rounded-[2px]"
            style={GRADIENT_BRAND}
          >
            Retry
          </button>
        </div>
      </div>
    );
  }

  // ============================================================
  // Loading State
  // ============================================================

  if (loading || !report) {
    return (
      <div className="max-w-[1200px] mx-auto px-6 space-y-8">
        <div className="h-9 w-48 rounded-[2px] bg-[var(--neutral-primary-soft)] animate-pulse" />
        <div className={cn(CARD, "h-24 animate-pulse")} />
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {[1, 2, 3, 4, 5, 6].map((i) => (
            <div
              key={i}
              className={cn(CARD, "h-48 animate-pulse")}
            />
          ))}
        </div>
      </div>
    );
  }

  // ============================================================
  // Render
  // ============================================================

  return (
    <div className="max-w-[1200px] mx-auto px-6 space-y-8">
      {/* Page Title */}
      <h1 className="text-[28px] font-semibold text-[var(--heading)]">
        Monthly Report
      </h1>

      {/* Report Header */}
      <div className={cn(CARD, "p-6 flex flex-col sm:flex-row sm:items-center justify-between gap-4")}>
        <div>
          <h2 className="text-[24px] font-semibold text-[var(--heading)]">
            {report.month} {report.year} Performance Report
          </h2>
          <p className="text-[14px] text-[var(--body)] mt-1 flex items-center gap-1.5">
            <Sparkles className="h-3.5 w-3.5 text-[var(--brand)]" />
            Generated by AI Report Agent
          </p>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={() => handleExport("CSV")}
            className="inline-flex items-center gap-1.5 px-4 py-2.5 text-[14px] font-medium text-[var(--body-subtle)] rounded-[2px] border border-[var(--border-default)] hover:text-[var(--heading)] transition-colors"
            style={{ backgroundColor: "transparent" }}
          >
            <Download className="h-3.5 w-3.5" />
            CSV
          </button>
          <button
            onClick={() => handleExport("Excel")}
            className="inline-flex items-center gap-1.5 px-4 py-2.5 text-[14px] font-medium text-[var(--body-subtle)] rounded-[2px] border border-[var(--border-default)] hover:text-[var(--heading)] transition-colors"
            style={{ backgroundColor: "transparent" }}
          >
            <Download className="h-3.5 w-3.5" />
            Excel
          </button>
          <button
            onClick={() => handleExport("Sheets")}
            className="inline-flex items-center gap-1.5 px-4 py-2.5 text-[14px] font-semibold text-white rounded-[2px]"
            style={GRADIENT_BRAND}
          >
            <Download className="h-3.5 w-3.5" />
            Sheets
          </button>
        </div>
      </div>

      {/* Report Sections */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {/* 1. Revenue Overview */}
        <div className={cn(CARD, "p-5")}>
          <div className="flex items-center gap-2 mb-3">
            <div
              className="flex items-center justify-center w-8 h-8 rounded-[2px]"
              style={{ backgroundColor: "var(--brand-softer)" }}
            >
              <DollarSign className="h-4 w-4 text-[var(--brand)]" />
            </div>
            <h3 className="text-[16px] font-semibold text-[var(--heading)]">
              Revenue Overview
            </h3>
          </div>
          <p className="text-[36px] font-semibold text-[var(--heading)]">
            {formatCurrency(report.totalRevenue)}
          </p>
          <div className="flex items-center gap-2 mt-2">
            <TrendingUp className="h-4 w-4 text-[var(--success)]" />
            <span className="text-[14px] font-semibold text-[var(--success)]">
              {formatPercent(report.revenueGrowth)}
            </span>
            <span className="text-[12px] text-[var(--body-subtle)]">
              vs last month
            </span>
          </div>
          <p className="text-[12px] text-[var(--body-subtle)] mt-2">
            {report.totalOrders.toLocaleString()} orders processed
          </p>
        </div>

        {/* 2. Marketing Summary */}
        <div className={cn(CARD, "p-5")}>
          <div className="flex items-center gap-2 mb-3">
            <div
              className="flex items-center justify-center w-8 h-8 rounded-[2px]"
              style={{ backgroundColor: "var(--warning-soft)" }}
            >
              <Megaphone className="h-4 w-4 text-[var(--warning)]" />
            </div>
            <h3 className="text-[16px] font-semibold text-[var(--heading)]">
              Marketing
            </h3>
          </div>
          <div className="space-y-2.5">
            <div className="flex justify-between items-center">
              <span className="text-[14px] text-[var(--body)]">Total Spend</span>
              <span className="text-[14px] font-semibold text-[var(--heading)]">
                {formatCurrency(report.totalMarketingSpend)}
              </span>
            </div>
            <div className="flex justify-between items-center">
              <span className="text-[14px] text-[var(--body)]">Avg ROAS</span>
              <span className="text-[14px] font-semibold text-[var(--success)]">
                {report.averageROAS}x
              </span>
            </div>
            <div className="flex justify-between items-center">
              <span className="text-[14px] text-[var(--body)]">
                Top Channel
              </span>
              <span className="text-[14px] font-semibold text-[var(--heading)]">
                {report.topPerformingChannel}
              </span>
            </div>
          </div>
        </div>

        {/* 3. Top Products */}
        <div className={cn(CARD, "p-5")}>
          <div className="flex items-center gap-2 mb-3">
            <div
              className="flex items-center justify-center w-8 h-8 rounded-[2px]"
              style={{ backgroundColor: "rgba(139,92,246,0.12)" }}
            >
              <Package className="h-4 w-4 text-[var(--purple)]" />
            </div>
            <h3 className="text-[16px] font-semibold text-[var(--heading)]">
              Top Products
            </h3>
          </div>
          <div className="space-y-2">
            {report.topProducts.map((p, i) => (
              <div
                key={p.sku}
                className="flex items-center justify-between"
              >
                <div className="min-w-0 flex-1">
                  <p className="text-[14px] text-[var(--heading)] truncate">
                    {p.name}
                  </p>
                  <p className="text-[12px] text-[var(--body-subtle)] font-mono">
                    {p.sku}
                  </p>
                </div>
                <span className="text-[14px] font-semibold text-[var(--heading)] shrink-0 ml-2">
                  {formatCurrency(p.revenue)}
                </span>
              </div>
            ))}
          </div>
        </div>

        {/* 4. Channel Breakdown */}
        <div className={cn(CARD, "p-5")}>
          <div className="flex items-center gap-2 mb-3">
            <div
              className="flex items-center justify-center w-8 h-8 rounded-[2px]"
              style={{ backgroundColor: "rgba(139,92,246,0.12)" }}
            >
              <ArrowUpRight className="h-4 w-4 text-[var(--purple)]" />
            </div>
            <h3 className="text-[16px] font-semibold text-[var(--heading)]">
              Channel Breakdown
            </h3>
          </div>
          <div className="space-y-3">
            {report.channels.slice(0, 5).map((ch, i) => (
              <div key={ch.name}>
                <div className="flex items-center justify-between mb-1">
                  <div className="flex items-center gap-2">
                    <span className="text-[12px] text-[var(--body-subtle)] w-10 tabular-nums">
                      {ch.percentage}%
                    </span>
                    <span className="text-[14px] text-[var(--body)]">
                      {ch.name}
                    </span>
                  </div>
                  <span className="text-[14px] font-semibold text-[var(--heading)]">
                    {formatCurrency(ch.revenue)}
                  </span>
                </div>
                <div
                  className="h-1.5 rounded-[2px] overflow-hidden"
                  style={{ backgroundColor: "var(--neutral-primary-medium)" }}
                >
                  <div
                    className="h-full rounded-[2px]"
                    style={{
                      width: `${ch.percentage}%`,
                      backgroundColor:
                        CHANNEL_COLORS[i % CHANNEL_COLORS.length],
                    }}
                  />
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* 5. Top Collection */}
        <div className={cn(CARD, "p-5")}>
          <div className="flex items-center gap-2 mb-3">
            <div
              className="flex items-center justify-center w-8 h-8 rounded-[2px]"
              style={{ backgroundColor: "var(--success-soft)" }}
            >
              <Star className="h-4 w-4 text-[var(--success)]" />
            </div>
            <h3 className="text-[16px] font-semibold text-[var(--heading)]">
              Top Collection
            </h3>
          </div>
          <p className="text-[16px] font-semibold text-[var(--heading)]">
            {report.topPerformingCollection}
          </p>
          <p className="text-[12px] text-[var(--body-subtle)] mt-1">
            Highest revenue collection
          </p>
          <div className="mt-4 space-y-2">
            <div className="flex items-center justify-between">
              <span className="text-[14px] text-[var(--body)]">
                Customer Satisfaction
              </span>
              <span className="text-[14px] font-semibold text-[var(--success)]">
                {report.customerSatisfaction}%
              </span>
            </div>
            <div className="flex items-center justify-between">
              <span className="text-[14px] text-[var(--body)]">
                Inventory Health
              </span>
              <span className="text-[14px] font-semibold text-[var(--heading)]">
                {report.inventoryHealth}
              </span>
            </div>
          </div>
        </div>

        {/* 6. Key Highlights */}
        <div className={cn(CARD, "p-5")}>
          <div className="flex items-center gap-2 mb-3">
            <div
              className="flex items-center justify-center w-8 h-8 rounded-[2px]"
              style={{ backgroundColor: "var(--brand-softer)" }}
            >
              <Star className="h-4 w-4 text-[var(--brand)]" />
            </div>
            <h3 className="text-[16px] font-semibold text-[var(--heading)]">
              Key Highlights
            </h3>
          </div>
          <ul className="space-y-2.5">
            {report.highlights.map((h, i) => (
              <li
                key={i}
                className="flex items-start gap-2"
              >
                <Star className="h-3 w-3 text-[var(--brand)] mt-0.5 shrink-0" />
                <span className="text-[14px] text-[var(--body)]">{h}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>

      {/* AI Watermark */}
      <div className="text-center pb-4">
        <p className="text-[12px] text-[var(--body-subtle)] flex items-center justify-center gap-1.5">
          <Sparkles className="h-3 w-3 text-[var(--brand)]" />
          This report was generated by your AI Report Agent
        </p>
      </div>
    </div>
  );
}
